export const PROTOTYPES = [
  {
    id: "student-profile",
    name: "Student Profile",
    section: "Prototypes",
    href: "/bs-prototypes/student-profile/",
    accent: "#E8866A",
    description: "Reading habits, skills, motivation & integrity dashboard for a single student.",
  },
  {
    id: "ris-school",
    name: "Reading Information System: School",
    section: "Prototypes",
    href: "/bs-prototypes/ris/",
    accent: "#1D4ED8",
    description: "School-level analytics dashboard for principals and instructional coaches.",
  },
  {
    id: "ris-district",
    name: "Reading Information System: District",
    section: "Prototypes",
    href: "/bs-prototypes/ris-district/",
    accent: "#0DA7BC",
    description: "District-level analytics dashboard for curriculum directors and superintendents.",
  },
  {
    id: "sfr",
    name: "Sessions for Review",
    section: "Prototypes",
    href: "/bs-prototypes/sfr/",
    accent: "#16A97A",
    description: "Redesigned Sessions for Review with AI summary, engagement highlights, and combined Book Talk list.",
  },
  {
    id: "admin-dashboard",
    name: "Admin Dashboard v2",
    section: "Prototypes",
    href: "/bs-prototypes/admin-dashboard/",
    accent: "#1A6DD5",
    description: "Editable admin dashboard with drag-and-drop, resizable, lockable widgets.",
  },
  {
    id: "rostering",
    name: "Rostering",
    section: "Prototypes",
    href: "/bs-prototypes/rostering/",
    accent: "#7C5CFA",
    description: "Preview what's coming in from Clever, filter classroom subjects, and manage roster syncs from one place.",
  },
  {
    id: "web-app",
    name: "Web App",
    section: "Experiments",
    href: "/bs-prototypes/web-app/",
    accent: "#0DA7BC",
    description: "Beanstack consumer web app — student-facing dashboard, challenges, reading log.",
  },
  {
    id: "footers",
    name: "Unified Joyful Footer",
    section: "Experiments",
    href: "/bs-prototypes/footers/",
    accent: "#7C5CFA",
    description: "A consistent Joyful-brand footer applied to Comics Plus, MyDot, Beanstack, and RMI Classroom — with dark/light mode.",
  },
  {
    id: "patterns",
    name: "Pattern Library",
    section: "Prototypes",
    href: "/bs-prototypes/patterns/",
    accent: "#7C3AED",
    description: "Shared components used across all RIS prototypes — StatCard, ChartCard, tooltips, icons.",
  },
];
