export const PROTOTYPES = [
  {
    id: 'challenge-creator',
    name: 'Challenge Creator v2',
    section: 'Experiments',
    category: 'Challenges',
    href: '/bs-prototypes/challenge-creator/',
    accent: '#F0A024',
    description: 'Full-screen wizard to create reading challenges — types, badges, rewards.',
  },
  {
    id: 'student-profile',
    name: 'Student Profile',
    section: 'Prototypes',
    category: 'Profiles',
    href: '/bs-prototypes/student-profile/',
    accent: '#E8866A',
    description: 'Single-student habits, skills, motivation & integrity.',
  },
  {
    id: 'reader-profile',
    name: 'Reader Profile',
    section: 'Prototypes',
    category: 'Profiles',
    href: '/bs-prototypes/reader-profile/',
    accent: '#0DA7BC',
    description: 'Library reader profile — one account, many readers.',
  },
  {
    id: 'ris-school',
    name: 'Reading Information System: School',
    section: 'Prototypes',
    category: 'Analytics',
    href: '/bs-prototypes/ris/',
    accent: '#1D4ED8',
    description: 'School analytics for principals & coaches.',
  },
  {
    id: 'ris-district',
    name: 'Reading Information System: District',
    section: 'Prototypes',
    category: 'Analytics',
    href: '/bs-prototypes/ris-district/',
    accent: '#0DA7BC',
    description: 'District analytics for curriculum & superintendents.',
  },
  {
    id: 'sfr',
    name: 'Sessions for Review',
    section: 'Completed',
    category: 'Reading integrity',
    href: '/bs-prototypes/sfr/',
    accent: '#16A97A',
    description: 'Review Book Talks for integrity, engagement, and student-safety signals.',
  },
  {
    id: 'admin-dashboard',
    name: 'Admin Dashboard v2',
    section: 'Completed',
    category: 'Admin',
    href: '/bs-prototypes/admin-dashboard/',
    accent: '#1A6DD5',
    description: 'Editable dashboard with drag-and-drop widgets.',
  },
  {
    id: 'rostering',
    name: 'Rostering: School',
    section: 'Completed',
    category: 'Rostering',
    href: '/bs-prototypes/rostering/',
    accent: '#7C5CFA',
    description: 'Clever roster sync — preview, filter, manage.',
  },
  {
    id: 'rostering-district',
    name: 'Rostering: District',
    section: 'Completed',
    category: 'Rostering',
    href: '/bs-prototypes/rostering-district/',
    accent: '#5B3FC8',
    description: 'District-wide roster sync filters & previews.',
  },
  {
    id: 'insights',
    name: 'Insights · Load Concepts',
    section: 'Experiments',
    category: 'Analytics',
    href: '/bs-prototypes/insights/',
    accent: '#6366F1',
    description: 'Lighter Insights load — snapshot, drill-down, progressive.',
  },
  {
    id: 'web-app',
    name: 'Web App',
    section: 'Experiments',
    category: 'Reader experience',
    href: '/bs-prototypes/web-app/',
    accent: '#0DA7BC',
    description: 'Student-facing dashboard, challenges, reading log.',
  },
  {
    id: 'footers',
    name: 'Unified Joyful Footer',
    section: 'Completed',
    category: 'Admin',
    href: '/bs-prototypes/footers/',
    accent: '#7C5CFA',
    description: 'Joyful footer across Comics Plus, MyDot, Beanstack, RMI.',
  },
  {
    id: 'patterns',
    name: 'Pattern Library',
    section: 'Prototypes',
    href: '/bs-prototypes/patterns/',
    accent: '#7C3AED',
    description: 'Shared RIS components — cards, charts, tooltips, icons.',
  },
  {
    id: 'book-talks',
    name: 'Book Talks: Badges',
    section: 'Prototypes',
    category: 'Book Talks',
    href: '/bs-prototypes/book-talks/',
    accent: '#14B8A6',
    description: 'Self-contained Benny Book Talk activity badge — chat to earn it.',
  },
  {
    id: 'books',
    name: 'Book Discovery',
    section: 'Prototypes',
    category: 'Reader experience',
    href: '/bs-prototypes/books/',
    accent: '#0D9488',
    description:
      'Reader-facing book pages — discover, reviews, Benny recommendations, and partner shelves.',
  },
  {
    id: 'logging-flow',
    name: 'Scholastic Logging Flow',
    section: 'Prototypes',
    category: 'Integrations',
    href: '/bs-prototypes/logging-flow/',
    accent: '#1A6DD5',
    description:
      'Beanstack combined reading-log flow, built around a Scholastic magazines reading list — search, log minutes/pages, timer, review.',
  },
  {
    id: 'pick-your-path',
    name: 'Pick Your Path',
    section: 'Prototypes',
    category: 'Challenges',
    href: '/bs-prototypes/pick-your-path/',
    accent: '#0F766E',
    description:
      'Teacher sets a vocabulary Destination; students pick a high-interest Path to practice the words and earn badges.',
  },
  {
    id: 'btwb',
    name: 'Book Talks: Comprehension',
    section: 'Prototypes',
    category: 'Book Talks',
    href: '/bs-prototypes/btwb/',
    accent: '#0E7490',
    description:
      'Site-wide BTWB setting — start a book talk on every completed book, on by default.',
  },
  {
    id: 'gameboard',
    name: 'Gameboard: Admin View',
    section: 'Prototypes',
    category: 'Challenges',
    href: '/bs-prototypes/gameboard/',
    accent: '#5FA052',
    description: 'Theme a gameboard and place badges along the path readers travel.',
  },
  {
    id: 'gameboard-reader',
    name: 'Gameboard: Reader View',
    section: 'Prototypes',
    category: 'Challenges',
    href: '/bs-prototypes/gameboard-reader/',
    accent: '#65A30D',
    description: 'How a reader travels the gameboard — log, unlock, celebrate.',
  },
  {
    id: 'beeverso',
    name: 'Beeverso Integration',
    section: 'Prototypes',
    category: 'Integrations',
    href: '/bs-prototypes/beeverso/',
    accent: '#662D91',
    description: 'Link a Beeverso account — Spanish reading logs itself in Beanstack.',
  },
  {
    id: 'words-with-benny',
    name: 'Words with Benny',
    section: 'Prototypes',
    category: 'Reader experience',
    href: '/bs-prototypes/words-with-benny/',
    accent: '#7C3AED',
    description:
      'Log reading, unlock a word from the book — collect them, and educators see the growth.',
  },
]
