export const PROTOTYPES = [
  {
    id: 'challenge-creator',
    name: 'Challenge Creator v2',
    section: 'Experiments',
    href: '/bs-prototypes/challenge-creator/',
    accent: '#F0A024',
    description: 'Full-screen wizard to create reading challenges — types, badges, rewards.',
  },
  {
    id: 'student-profile',
    name: 'Student Profile',
    section: 'Prototypes',
    href: '/bs-prototypes/student-profile/',
    accent: '#E8866A',
    description: 'Single-student habits, skills, motivation & integrity.',
  },
  {
    id: 'ris-school',
    name: 'Reading Information System: School',
    section: 'Prototypes',
    href: '/bs-prototypes/ris/',
    accent: '#1D4ED8',
    description: 'School analytics for principals & coaches.',
  },
  {
    id: 'ris-district',
    name: 'Reading Information System: District',
    section: 'Prototypes',
    href: '/bs-prototypes/ris-district/',
    accent: '#0DA7BC',
    description: 'District analytics for curriculum & superintendents.',
  },
  {
    id: 'sfr',
    name: 'Sessions for Review',
    section: 'Prototypes',
    href: '/bs-prototypes/sfr/',
    accent: '#16A97A',
    description: 'Redesigned Sessions for Review with AI summary.',
  },
  {
    id: 'admin-dashboard',
    name: 'Admin Dashboard v2',
    section: 'Prototypes',
    href: '/bs-prototypes/admin-dashboard/',
    accent: '#1A6DD5',
    description: 'Editable dashboard with drag-and-drop widgets.',
  },
  {
    id: 'rostering',
    name: 'Rostering: School',
    section: 'Prototypes',
    href: '/bs-prototypes/rostering/',
    accent: '#7C5CFA',
    description: 'Clever roster sync — preview, filter, manage.',
  },
  {
    id: 'rostering-district',
    name: 'Rostering: District',
    section: 'Prototypes',
    href: '/bs-prototypes/rostering-district/',
    accent: '#5B3FC8',
    description: 'District-wide roster sync filters & previews.',
  },
  {
    id: 'insights',
    name: 'Insights · Load Concepts',
    section: 'Prototypes',
    href: '/bs-prototypes/insights/',
    accent: '#6366F1',
    description: 'Lighter Insights load — snapshot, drill-down, progressive.',
  },
  {
    id: 'web-app',
    name: 'Web App',
    section: 'Experiments',
    href: '/bs-prototypes/web-app/',
    accent: '#0DA7BC',
    description: 'Student-facing dashboard, challenges, reading log.',
  },
  {
    id: 'footers',
    name: 'Unified Joyful Footer',
    section: 'Experiments',
    href: '/bs-prototypes/footers/',
    accent: '#7C5CFA',
    description: 'Joyful footer across Comics Plus, MyDot, Beanstack, RMI.',
  },
  {
    id: 'patterns',
    name: 'Pattern Library',
    section: 'Prototypes',
    href: '/bs-prototypes/patterns/',
    accent: '#7C3AED',
    description: 'Shared RIS components — cards, charts, tooltips, icons.',
  },
]
