// Title pool for the RMI genre recommendations — 414 books for grades 3–5,
// filed under the toolkit's own genre names.
//
// The chain the doc asks for runs motivation type → genre → title, so the pool
// is keyed by genre: a type's three genres are three lists, and a list is the
// books filed under it. Filing them directly rather than deriving a genre from
// a catalogue tag keeps the label on a book honest — a book sits under
// "Puzzle/Interactive Books" because it is one, not because it shares a coarse
// tag with one.
//
// Every record is a real book, and `coverId` is its Open Library cover, each
// one checked to resolve. What a record asserts is its title and author plus
// two curatorial judgements: which genre shelf it belongs on, and that it suits
// ages 8–12. In the product both would come from Book Contexts, where the doc
// asks JRC to add a grade level and an RMI type association to each title.

/** Ages the whole pool is curated for — grades 3 through 5. */
const AGES = '8\u201312'

export const TITLES_BY_GENRE = {
  'Epic Fantasy': [
    {
      id: 'the-lion-the-witch-and',
      coverId: 8441376,
      title: 'The Lion, the Witch and the Wardrobe',
      author: 'C. S. Lewis',
      ageRange: AGES,
    },
    {
      id: 'the-hobbit',
      coverId: 14627509,
      title: 'The Hobbit',
      author: 'J. R. R. Tolkien',
      ageRange: AGES,
    },
    {
      id: 'wings-of-fire-the-dragonet',
      coverId: 13460810,
      title: 'Wings of Fire: The Dragonet Prophecy',
      author: 'Tui T. Sutherland',
      ageRange: AGES,
    },
    {
      id: 'dragon-rider',
      coverId: 3330355,
      title: 'Dragon Rider',
      author: 'Cornelia Funke',
      ageRange: AGES,
    },
    {
      id: 'the-land-of-stories-the',
      coverId: 7254710,
      title: 'The Land of Stories: The Wishing Spell',
      author: 'Chris Colfer',
      ageRange: AGES,
    },
    {
      id: 'nevermoor-the-trials-of-morrigan',
      coverId: 8458528,
      title: 'Nevermoor: The Trials of Morrigan Crow',
      author: 'Jessica Townsend',
      ageRange: AGES,
    },
    {
      id: 'aru-shah-and-the-end',
      coverId: 8184341,
      title: 'Aru Shah and the End of Time',
      author: 'Roshani Chokshi',
      ageRange: AGES,
    },
    {
      id: 'the-girl-who-drank-the',
      coverId: 7903958,
      title: 'The Girl Who Drank the Moon',
      author: 'Kelly Barnhill',
      ageRange: AGES,
    },
    {
      id: 'tristan-strong-punches-a-hole',
      coverId: 9120341,
      title: 'Tristan Strong Punches a Hole in the Sky',
      author: 'Kwame Mbalia',
      ageRange: AGES,
    },
    {
      id: 'prince-caspian',
      coverId: 45897,
      title: 'Prince Caspian',
      author: 'C. S. Lewis',
      ageRange: AGES,
    },
    {
      id: 'the-ruins-of-gorlan',
      coverId: 6401507,
      title: 'The Ruins of Gorlan',
      author: 'John Flanagan',
      ageRange: AGES,
    },
    { id: 'redwall', coverId: 2325082, title: 'Redwall', author: 'Brian Jacques', ageRange: AGES },
    {
      id: 'the-dark-is-rising',
      coverId: 9363540,
      title: 'The Dark Is Rising',
      author: 'Susan Cooper',
      ageRange: AGES,
    },
    {
      id: 'sal-and-gabi-break-the',
      coverId: 10894894,
      title: 'Sal and Gabi Break the Universe',
      author: 'Carlos Hernandez',
      ageRange: AGES,
    },
    {
      id: 'the-dragon-with-a-chocolate',
      coverId: 10513803,
      title: 'The Dragon with a Chocolate Heart',
      author: 'Stephanie Burgis',
      ageRange: AGES,
    },
  ],
  'Historical Fiction': [
    {
      id: 'number-the-stars',
      coverId: 13249599,
      title: 'Number the Stars',
      author: 'Lois Lowry',
      ageRange: AGES,
    },
    {
      id: 'sarah-plain-and-tall',
      coverId: 8144459,
      title: 'Sarah, Plain and Tall',
      author: 'Patricia MacLachlan',
      ageRange: AGES,
    },
    {
      id: 'the-war-that-saved-my',
      coverId: 7410332,
      title: 'The War That Saved My Life',
      author: 'Kimberly Brubaker Bradley',
      ageRange: AGES,
    },
    {
      id: 'bud-not-buddy',
      coverId: 9342833,
      title: 'Bud, Not Buddy',
      author: 'Christopher Paul Curtis',
      ageRange: AGES,
    },
    {
      id: 'blood-on-the-river',
      coverId: 1119207,
      title: 'Blood on the River',
      author: 'Elisa Carbone',
      ageRange: AGES,
    },
    {
      id: 'al-capone-does-my-shirts',
      coverId: 8790938,
      title: 'Al Capone Does My Shirts',
      author: 'Gennifer Choldenko',
      ageRange: AGES,
    },
    {
      id: 'the-birchbark-house',
      coverId: 1469978,
      title: 'The Birchbark House',
      author: 'Louise Erdrich',
      ageRange: AGES,
    },
    {
      id: 'chains',
      coverId: 5342043,
      title: 'Chains',
      author: 'Laurie Halse Anderson',
      ageRange: AGES,
    },
    {
      id: 'a-night-divided',
      coverId: 8810403,
      title: 'A Night Divided',
      author: 'Jennifer A. Nielsen',
      ageRange: AGES,
    },
    { id: 'echo', coverId: 11172044, title: 'Echo', author: 'Pam Munoz Ryan', ageRange: AGES },
    {
      id: 'the-green-glass-sea',
      coverId: 6800515,
      title: 'The Green Glass Sea',
      author: 'Ellen Klages',
      ageRange: AGES,
    },
    {
      id: 'turtle-in-paradise',
      coverId: 6412155,
      title: 'Turtle in Paradise',
      author: 'Jennifer L. Holm',
      ageRange: AGES,
    },
    {
      id: 'little-house-in-the-big',
      coverId: 28677,
      title: 'Little House in the Big Woods',
      author: 'Laura Ingalls Wilder',
      ageRange: AGES,
    },
    {
      id: 'prairie-lotus',
      coverId: 9294526,
      title: 'Prairie Lotus',
      author: 'Linda Sue Park',
      ageRange: AGES,
    },
  ],
  'Biographies of Leaders': [
    {
      id: 'who-was-harriet-tubman',
      coverId: 1236038,
      title: 'Who Was Harriet Tubman?',
      author: 'Yona Zeldis McDonough',
      ageRange: AGES,
    },
    {
      id: 'i-am-malala-how-one',
      coverId: 7290567,
      title: 'I Am Malala: How One Girl Stood Up for Education',
      author: 'Malala Yousafzai',
      ageRange: AGES,
    },
    {
      id: 'martins-big-words',
      coverId: 1817793,
      title: "Martin's Big Words",
      author: 'Doreen Rappaport',
      ageRange: AGES,
    },
    {
      id: 'who-was-abraham-lincoln',
      coverId: 7258584,
      title: 'Who Was Abraham Lincoln?',
      author: 'Janet B. Pascal',
      ageRange: AGES,
    },
    {
      id: 'she-persisted',
      coverId: 8106956,
      title: 'She Persisted',
      author: 'Chelsea Clinton',
      ageRange: AGES,
    },
    {
      id: 'who-was-rosa-parks',
      coverId: 7401215,
      title: 'Who Was Rosa Parks?',
      author: 'Yona Zeldis McDonough',
      ageRange: AGES,
    },
    {
      id: 'who-was-gandhi',
      coverId: 8476202,
      title: 'Who Was Gandhi?',
      author: 'Dana Meachen Rau',
      ageRange: AGES,
    },
    {
      id: 'who-was-cesar-chavez',
      coverId: 8136664,
      title: 'Who Was Cesar Chavez?',
      author: 'Dana Meachen Rau',
      ageRange: AGES,
    },
    {
      id: 'who-was-frederick-douglass',
      coverId: 8744183,
      title: 'Who Was Frederick Douglass?',
      author: 'April Jones Prince',
      ageRange: AGES,
    },
    {
      id: 'who-was-anne-frank',
      coverId: 12991521,
      title: 'Who Was Anne Frank?',
      author: 'Ann Abramson',
      ageRange: AGES,
    },
    {
      id: 'preaching-to-the-chickens',
      coverId: 7911485,
      title: 'Preaching to the Chickens',
      author: 'Jabari Asim',
      ageRange: AGES,
    },
    {
      id: 'the-youngest-marcher',
      coverId: 10523430,
      title: 'The Youngest Marcher',
      author: 'Cynthia Levinson',
      ageRange: AGES,
    },
    {
      id: 'separate-is-never-equal',
      coverId: 14562286,
      title: 'Separate Is Never Equal',
      author: 'Duncan Tonatiuh',
      ageRange: AGES,
    },
  ],
  'Dystopian/Sci-Fi': [
    {
      id: 'the-city-of-ember',
      coverId: 14421081,
      title: 'The City of Ember',
      author: 'Jeanne DuPrau',
      ageRange: AGES,
    },
    {
      id: 'among-the-hidden',
      coverId: 1319159,
      title: 'Among the Hidden',
      author: 'Margaret Peterson Haddix',
      ageRange: AGES,
    },
    {
      id: 'space-case',
      coverId: 7322003,
      title: 'Space Case',
      author: 'Stuart Gibbs',
      ageRange: AGES,
    },
    {
      id: 'the-lion-of-mars',
      coverId: 10696289,
      title: 'The Lion of Mars',
      author: 'Jennifer L. Holm',
      ageRange: AGES,
    },
    {
      id: 'cosmic',
      coverId: 10097128,
      title: 'Cosmic',
      author: 'Frank Cottrell Boyce',
      ageRange: AGES,
    },
    {
      id: 'the-mysterious-benedict-society',
      coverId: 2378898,
      title: 'The Mysterious Benedict Society',
      author: 'Trenton Lee Stewart',
      ageRange: AGES,
    },
    {
      id: 'the-last-cuentista',
      coverId: 12579345,
      title: 'The Last Cuentista',
      author: 'Donna Barba Higuera',
      ageRange: AGES,
    },
    {
      id: 'sanctuary',
      coverId: 10431434,
      title: 'Sanctuary',
      author: 'Paola Mendoza',
      ageRange: AGES,
    },
    {
      id: 'the-wild-robot-protects',
      coverId: 13175129,
      title: 'The Wild Robot Protects',
      author: 'Peter Brown',
      ageRange: AGES,
    },
    {
      id: 'the-fourteenth-goldfish',
      coverId: 7357590,
      title: 'The Fourteenth Goldfish',
      author: 'Jennifer L. Holm',
      ageRange: AGES,
    },
    {
      id: 'the-girl-who-could-fly',
      coverId: 6303763,
      title: 'The Girl Who Could Fly',
      author: 'Victoria Forester',
      ageRange: AGES,
    },
    {
      id: 'frank-einstein-and-the-antimatter',
      coverId: 7347040,
      title: 'Frank Einstein and the Antimatter Motor',
      author: 'Jon Scieszka',
      ageRange: AGES,
    },
    {
      id: 'the-last-human',
      coverId: 9161795,
      title: 'The Last Human',
      author: 'Lee Bacon',
      ageRange: AGES,
    },
    {
      id: 'ghost-squad',
      coverId: 9324164,
      title: 'Ghost Squad',
      author: 'Claribel A. Ortega',
      ageRange: AGES,
    },
  ],
  'Survival/Adventure': [
    {
      id: 'i-survived-the-sinking-of',
      coverId: 6669375,
      title: 'I Survived the Sinking of the Titanic, 1912',
      author: 'Lauren Tarshis',
      ageRange: AGES,
    },
    {
      id: 'island-of-the-blue-dolphins',
      coverId: 5021868,
      title: 'Island of the Blue Dolphins',
      author: "Scott O'Dell",
      ageRange: AGES,
    },
    {
      id: 'the-sign-of-the-beaver',
      coverId: 5140026,
      title: 'The Sign of the Beaver',
      author: 'Elizabeth George Speare',
      ageRange: AGES,
    },
    { id: 'peak', coverId: 1120257, title: 'Peak', author: 'Roland Smith', ageRange: AGES },
    {
      id: 'a-long-walk-to-water',
      coverId: 7350927,
      title: 'A Long Walk to Water',
      author: 'Linda Sue Park',
      ageRange: AGES,
    },
    {
      id: 'my-side-of-the-mountain',
      coverId: 108669,
      title: 'My Side of the Mountain',
      author: 'Jean Craighead George',
      ageRange: AGES,
    },
    {
      id: 'brians-winter',
      coverId: 239344,
      title: "Brian's Winter",
      author: 'Gary Paulsen',
      ageRange: AGES,
    },
    {
      id: 'julie-of-the-wolves',
      coverId: 12903627,
      title: 'Julie of the Wolves',
      author: 'Jean Craighead George',
      ageRange: AGES,
    },
    {
      id: 'i-survived-the-attacks-of',
      coverId: 7346358,
      title: 'I Survived the Attacks of September 11, 2001',
      author: 'Lauren Tarshis',
      ageRange: AGES,
    },
    {
      id: 'the-explorer',
      coverId: 14621738,
      title: 'The Explorer',
      author: 'Katherine Rundell',
      ageRange: AGES,
    },
    { id: 'the-cay', coverId: 234731, title: 'The Cay', author: 'Theodore Taylor', ageRange: AGES },
    {
      id: 'the-call-of-the-wild',
      coverId: 12393037,
      title: 'The Call of the Wild',
      author: 'Jack London',
      ageRange: AGES,
    },
    {
      id: 'brians-return',
      coverId: 8016485,
      title: "Brian's Return",
      author: 'Gary Paulsen',
      ageRange: AGES,
    },
    {
      id: 'lost-in-the-barrens',
      coverId: 530643,
      title: 'Lost in the Barrens',
      author: 'Farley Mowat',
      ageRange: AGES,
    },
  ],
  'Realistic Fiction (Complex Themes)': [
    {
      id: 'counting-by-7s',
      coverId: 7590471,
      title: 'Counting by 7s',
      author: 'Holly Goldberg Sloan',
      ageRange: AGES,
    },
    {
      id: 'the-thing-about-jellyfish',
      coverId: 9280430,
      title: 'The Thing About Jellyfish',
      author: 'Ali Benjamin',
      ageRange: AGES,
    },
    {
      id: 'bridge-to-terabithia',
      coverId: 12627341,
      title: 'Bridge to Terabithia',
      author: 'Katherine Paterson',
      ageRange: AGES,
    },
    {
      id: 'because-of-mr-terupt',
      coverId: 8311480,
      title: 'Because of Mr. Terupt',
      author: 'Rob Buyea',
      ageRange: AGES,
    },
    {
      id: 'rain-reign',
      coverId: 7399827,
      title: 'Rain Reign',
      author: 'Ann M. Martin',
      ageRange: AGES,
    },
    {
      id: 'walk-two-moons',
      coverId: 5283748,
      title: 'Walk Two Moons',
      author: 'Sharon Creech',
      ageRange: AGES,
    },
    {
      id: 'maniac-magee',
      coverId: 10134677,
      title: 'Maniac Magee',
      author: 'Jerry Spinelli',
      ageRange: AGES,
    },
    {
      id: 'hello-universe',
      coverId: 8803519,
      title: 'Hello, Universe',
      author: 'Erin Entrada Kelly',
      ageRange: AGES,
    },
    {
      id: 'the-war-i-finally-won',
      coverId: 8465177,
      title: 'The War I Finally Won',
      author: 'Kimberly Brubaker Bradley',
      ageRange: AGES,
    },
    {
      id: 'crenshaw',
      coverId: 12656561,
      title: 'Crenshaw',
      author: 'Katherine Applegate',
      ageRange: AGES,
    },
    {
      id: 'auggie-me',
      coverId: 7389807,
      title: 'Auggie & Me',
      author: 'R. J. Palacio',
      ageRange: AGES,
    },
    {
      id: 'see-you-in-the-cosmos',
      coverId: 8803792,
      title: 'See You in the Cosmos',
      author: 'Jack Cheng',
      ageRange: AGES,
    },
    {
      id: 'the-remarkable-journey-of-coyote',
      coverId: 8801784,
      title: 'The Remarkable Journey of Coyote Sunrise',
      author: 'Dan Gemeinhart',
      ageRange: AGES,
    },
    {
      id: 'wolf-hollow',
      coverId: 15090560,
      title: 'Wolf Hollow',
      author: 'Lauren Wolk',
      ageRange: AGES,
    },
  ],
  'Mystery/Whodunit': [
    {
      id: 'the-westing-game',
      coverId: 6973801,
      title: 'The Westing Game',
      author: 'Ellen Raskin',
      ageRange: AGES,
    },
    {
      id: 'from-the-mixed-up-files',
      coverId: 541206,
      title: 'From the Mixed-Up Files of Mrs. Basil E. Frankweiler',
      author: 'E. L. Konigsburg',
      ageRange: AGES,
    },
    {
      id: 'chasing-vermeer',
      coverId: 277450,
      title: 'Chasing Vermeer',
      author: 'Blue Balliett',
      ageRange: AGES,
    },
    {
      id: 'greenglass-house',
      coverId: 7347914,
      title: 'Greenglass House',
      author: 'Kate Milford',
      ageRange: AGES,
    },
    {
      id: 'the-london-eye-mystery',
      coverId: 6422457,
      title: 'The London Eye Mystery',
      author: 'Siobhan Dowd',
      ageRange: AGES,
    },
    {
      id: 'encyclopedia-brown-boy-detective',
      coverId: 3369815,
      title: 'Encyclopedia Brown, Boy Detective',
      author: 'Donald J. Sobol',
      ageRange: AGES,
    },
    {
      id: 'the-parker-inheritance',
      coverId: 10839245,
      title: 'The Parker Inheritance',
      author: 'Varian Johnson',
      ageRange: AGES,
    },
    { id: 'framed', coverId: 10582654, title: 'Framed!', author: 'James Ponti', ageRange: AGES },
    {
      id: 'book-scavenger',
      coverId: 9140681,
      title: 'Book Scavenger',
      author: 'Jennifer Chambliss Bertman',
      ageRange: AGES,
    },
    {
      id: 'the-van-gogh-deception',
      coverId: 14602813,
      title: 'The Van Gogh Deception',
      author: 'Deron R. Hicks',
      ageRange: AGES,
    },
    {
      id: 'sammy-keyes-and-the-hotel',
      coverId: 424094,
      title: 'Sammy Keyes and the Hotel Thief',
      author: 'Wendelin Van Draanen',
      ageRange: AGES,
    },
    {
      id: 'winterhouse',
      coverId: 8755943,
      title: 'Winterhouse',
      author: 'Ben Guterson',
      ageRange: AGES,
    },
    {
      id: 'the-case-of-the-missing',
      coverId: 260208,
      title: 'The Case of the Missing Marquess',
      author: 'Nancy Springer',
      ageRange: AGES,
    },
    {
      id: 'the-secret-of-the-old',
      coverId: 15144188,
      title: 'The Secret of the Old Clock',
      author: 'Carolyn Keene',
      ageRange: AGES,
    },
  ],
  'Puzzle/Interactive Books': [
    {
      id: 'escape-from-mr-lemoncellos-library',
      coverId: 7268631,
      title: "Escape from Mr. Lemoncello's Library",
      author: 'Chris Grabenstein',
      ageRange: AGES,
    },
    {
      id: 'mr-lemoncellos-great-library-race',
      coverId: 8811797,
      title: "Mr. Lemoncello's Great Library Race",
      author: 'Chris Grabenstein',
      ageRange: AGES,
    },
    {
      id: 'the-name-of-this-book',
      coverId: 6136549,
      title: 'The Name of This Book Is Secret',
      author: 'Pseudonymous Bosch',
      ageRange: AGES,
    },
    {
      id: 'the-abominable-snowman',
      coverId: 9720724,
      title: 'The Abominable Snowman',
      author: 'R. A. Montgomery',
      ageRange: AGES,
    },
    {
      id: 'journey-under-the-sea',
      coverId: 3062257,
      title: 'Journey Under the Sea',
      author: 'R. A. Montgomery',
      ageRange: AGES,
    },
    {
      id: 'the-puzzling-world-of-winston',
      coverId: 2413563,
      title: 'The Puzzling World of Winston Breen',
      author: 'Eric Berlin',
      ageRange: AGES,
    },
    {
      id: 'can-you-crack-the-code',
      coverId: 8800456,
      title: 'Can You Crack the Code?',
      author: 'Ella Schwartz',
      ageRange: AGES,
    },
    {
      id: 'the-mysterious-benedict-society-and',
      coverId: 6274740,
      title: 'The Mysterious Benedict Society and the Perilous Journey',
      author: 'Trenton Lee Stewart',
      ageRange: AGES,
    },
    {
      id: 'the-gollywhopper-games',
      coverId: 2313708,
      title: 'The Gollywhopper Games',
      author: 'Jody Feldman',
      ageRange: AGES,
    },
    {
      id: 'the-potato-chip-puzzles',
      coverId: 7091424,
      title: 'The Potato Chip Puzzles',
      author: 'Eric Berlin',
      ageRange: AGES,
    },
    {
      id: 'space-and-beyond',
      coverId: 3062258,
      title: 'Space and Beyond',
      author: 'R. A. Montgomery',
      ageRange: AGES,
    },
    {
      id: 'escape-this-book-titanic',
      coverId: 12380245,
      title: 'Escape This Book! Titanic',
      author: 'Bill Doyle',
      ageRange: AGES,
    },
    {
      id: 'can-you-survive-the-wilderness',
      coverId: 12895998,
      title: 'Can You Survive the Wilderness?',
      author: 'Matt Doeden',
      ageRange: AGES,
    },
    {
      id: 'the-inquisitors-tale',
      coverId: 7912602,
      title: "The Inquisitor's Tale",
      author: 'Adam Gidwitz',
      ageRange: AGES,
    },
  ],
  'Narrative Non-Fiction': [
    {
      id: 'bomb-the-race-to-build',
      coverId: 7236649,
      title: "Bomb: The Race to Build and Steal the World's Most Dangerous Weapon",
      author: 'Steve Sheinkin',
      ageRange: AGES,
    },
    {
      id: 'chasing-lincolns-killer',
      coverId: 6374127,
      title: "Chasing Lincoln's Killer",
      author: 'James L. Swanson',
      ageRange: AGES,
    },
    {
      id: 'the-boy-who-harnessed-the',
      coverId: 6447181,
      title: 'The Boy Who Harnessed the Wind',
      author: 'William Kamkwamba',
      ageRange: AGES,
    },
    {
      id: 'six-dots-a-story-of',
      coverId: 7876763,
      title: 'Six Dots: A Story of Young Louis Braille',
      author: 'Jen Bryant',
      ageRange: AGES,
    },
    {
      id: 'blizzard-of-glass',
      coverId: 7172258,
      title: 'Blizzard of Glass',
      author: 'Sally M. Walker',
      ageRange: AGES,
    },
    {
      id: 'titanic-voices-from-the-disaster',
      coverId: 7247819,
      title: 'Titanic: Voices from the Disaster',
      author: 'Deborah Hopkinson',
      ageRange: AGES,
    },
    {
      id: 'lincolns-grave-robbers',
      coverId: 8311753,
      title: "Lincoln's Grave Robbers",
      author: 'Steve Sheinkin',
      ageRange: AGES,
    },
    {
      id: 'the-great-fire',
      coverId: 929851,
      title: 'The Great Fire',
      author: 'Jim Murphy',
      ageRange: AGES,
    },
    {
      id: 'an-american-plague',
      coverId: 256836,
      title: 'An American Plague',
      author: 'Jim Murphy',
      ageRange: AGES,
    },
    {
      id: 'trapped-how-the-world-rescued',
      coverId: 6962447,
      title: 'Trapped: How the World Rescued 33 Miners from 2,000 Feet Below the Chilean Desert',
      author: 'Marc Aronson',
      ageRange: AGES,
    },
    {
      id: 'team-moon-how-400-000',
      coverId: 394761,
      title: 'Team Moon: How 400,000 People Landed Apollo 11',
      author: 'Catherine Thimmesh',
      ageRange: AGES,
    },
    {
      id: 'deadliest-creature-in-the-world',
      coverId: 13062512,
      title: 'Deadliest Creature in the World',
      author: 'Brenda Z. Guiberson',
      ageRange: AGES,
    },
  ],
  'Graphic Novels & Manga': [
    {
      id: 'bone-out-from-boneville',
      coverId: 12648893,
      title: 'Bone: Out from Boneville',
      author: 'Jeff Smith',
      ageRange: AGES,
    },
    {
      id: 'big-nate-in-a-class',
      coverId: 6389101,
      title: 'Big Nate: In a Class by Himself',
      author: 'Lincoln Peirce',
      ageRange: AGES,
    },
    {
      id: 'hilo-the-boy-who-crashed',
      coverId: 8904690,
      title: 'Hilo: The Boy Who Crashed to Earth',
      author: 'Judd Winick',
      ageRange: AGES,
    },
    {
      id: 'sunny-side-up',
      coverId: 10212682,
      title: 'Sunny Side Up',
      author: 'Jennifer L. Holm',
      ageRange: AGES,
    },
    {
      id: 'roller-girl',
      coverId: 11327078,
      title: 'Roller Girl',
      author: 'Victoria Jamieson',
      ageRange: AGES,
    },
    {
      id: 'zita-the-spacegirl',
      coverId: 6682674,
      title: 'Zita the Spacegirl',
      author: 'Ben Hatke',
      ageRange: AGES,
    },
    { id: 'snapdragon', coverId: 9322939, title: 'Snapdragon', author: 'Kat Leyh', ageRange: AGES },
    {
      id: 'the-stonekeepers-curse',
      coverId: 11514575,
      title: "The Stonekeeper's Curse",
      author: 'Kazu Kibuishi',
      ageRange: AGES,
    },
    {
      id: 'saving-the-whole-wide-world',
      coverId: 8904690,
      title: 'Saving the Whole Wide World',
      author: 'Judd Winick',
      ageRange: AGES,
    },
    {
      id: 'the-great-cow-race',
      coverId: 12648854,
      title: 'The Great Cow Race',
      author: 'Jeff Smith',
      ageRange: AGES,
    },
    { id: 'twins', coverId: 10289795, title: 'Twins', author: 'Varian Johnson', ageRange: AGES },
    {
      id: 'class-act',
      coverId: 10333026,
      title: 'Class Act',
      author: 'Jerry Craft',
      ageRange: AGES,
    },
    {
      id: 'allergic',
      coverId: 10724638,
      title: 'Allergic',
      author: 'Megan Wagner Lloyd',
      ageRange: AGES,
    },
    {
      id: 'measuring-up',
      coverId: 10096868,
      title: 'Measuring Up',
      author: 'Lily LaMotte',
      ageRange: AGES,
    },
  ],
  'Series/Franchise Books': [
    {
      id: 'the-bad-guys',
      coverId: 14420613,
      title: 'The Bad Guys',
      author: 'Aaron Blabey',
      ageRange: AGES,
    },
    {
      id: 'diary-of-a-wimpy-kid',
      coverId: 14376136,
      title: 'Diary of a Wimpy Kid',
      author: 'Jeff Kinney',
      ageRange: AGES,
    },
    {
      id: 'warriors-into-the-wild',
      coverId: 12720669,
      title: 'Warriors: Into the Wild',
      author: 'Erin Hunter',
      ageRange: AGES,
    },
    {
      id: 'dinosaurs-before-dark',
      coverId: 14390457,
      title: 'Dinosaurs Before Dark',
      author: 'Mary Pope Osborne',
      ageRange: AGES,
    },
    {
      id: 'the-sea-of-monsters',
      coverId: 108909,
      title: 'The Sea of Monsters',
      author: 'Rick Riordan',
      ageRange: AGES,
    },
    {
      id: 'wings-of-fire-the-lost',
      coverId: 7548609,
      title: 'Wings of Fire: The Lost Heir',
      author: 'Tui T. Sutherland',
      ageRange: AGES,
    },
    {
      id: 'the-maze-of-bones',
      coverId: 5723136,
      title: 'The Maze of Bones',
      author: 'Rick Riordan',
      ageRange: AGES,
    },
    {
      id: 'harry-potter-and-the-chamber',
      coverId: 15158664,
      title: 'Harry Potter and the Chamber of Secrets',
      author: 'J. K. Rowling',
      ageRange: AGES,
    },
    {
      id: 'the-titans-curse',
      coverId: 14601475,
      title: "The Titan's Curse",
      author: 'Rick Riordan',
      ageRange: AGES,
    },
    {
      id: 'the-furball-strikes-back',
      coverId: 8757201,
      title: 'The Furball Strikes Back',
      author: 'Aaron Blabey',
      ageRange: AGES,
    },
    {
      id: 'the-knight-at-dawn',
      coverId: 231998,
      title: 'The Knight at Dawn',
      author: 'Mary Pope Osborne',
      ageRange: AGES,
    },
    {
      id: 'fire-and-ice',
      coverId: 27365,
      title: 'Fire and Ice',
      author: 'Erin Hunter',
      ageRange: AGES,
    },
    {
      id: 'the-hidden-kingdom',
      coverId: 11243757,
      title: 'The Hidden Kingdom',
      author: 'Tui T. Sutherland',
      ageRange: AGES,
    },
    {
      id: 'the-lost-hero',
      coverId: 12848687,
      title: 'The Lost Hero',
      author: 'Rick Riordan',
      ageRange: AGES,
    },
  ],
  'Media Tie-ins': [
    {
      id: 'minecraft-the-island',
      coverId: 10568235,
      title: 'Minecraft: The Island',
      author: 'Max Brooks',
      ageRange: AGES,
    },
    {
      id: 'minecraft-the-crash',
      coverId: 8572412,
      title: 'Minecraft: The Crash',
      author: 'Tracey Baptiste',
      ageRange: AGES,
    },
    {
      id: 'star-wars-jedi-academy',
      coverId: 12722598,
      title: 'Star Wars: Jedi Academy',
      author: 'Jeffrey Brown',
      ageRange: AGES,
    },
    {
      id: 'pokemon-deluxe-essential-handbook',
      coverId: 8314253,
      title: 'Pokemon Deluxe Essential Handbook',
      author: 'Scholastic',
      ageRange: AGES,
    },
    {
      id: 'the-last-kids-on-earth',
      coverId: 8504472,
      title: 'The Last Kids on Earth and the Zombie Parade',
      author: 'Max Brallier',
      ageRange: AGES,
    },
    {
      id: 'five-nights-at-freddys-into',
      coverId: 9256631,
      title: "Five Nights at Freddy's: Into the Pit",
      author: 'Scott Cawthon',
      ageRange: AGES,
    },
    {
      id: 'sonic-the-hedgehog-sonics-adventures',
      coverId: 8217589,
      title: "Sonic the Hedgehog: Sonic's Adventures",
      author: 'Sega',
      ageRange: AGES,
    },
    {
      id: 'minecraft-the-voyage',
      coverId: 13474228,
      title: 'Minecraft: The Voyage',
      author: 'Jason Fry',
      ageRange: AGES,
    },
    {
      id: 'minecraft-the-mountain',
      coverId: 10606180,
      title: 'Minecraft: The Mountain',
      author: 'Max Brooks',
      ageRange: AGES,
    },
    {
      id: 'return-of-the-padawan',
      coverId: 12722573,
      title: 'Return of the Padawan',
      author: 'Jeffrey Brown',
      ageRange: AGES,
    },
    {
      id: 'minecraft-the-shipwreck',
      coverId: 11422196,
      title: 'Minecraft: The Shipwreck',
      author: 'C. B. Lee',
      ageRange: AGES,
    },
    {
      id: 'diary-of-an-8-bit',
      coverId: 10317807,
      title: 'Diary of an 8-Bit Warrior',
      author: 'Cube Kid',
      ageRange: AGES,
    },
    {
      id: 'the-phantom-bully',
      coverId: 12722587,
      title: 'The Phantom Bully',
      author: 'Jeffrey Brown',
      ageRange: AGES,
    },
    {
      id: 'minecraft-mob-squad',
      coverId: 12964247,
      title: 'Minecraft: Mob Squad',
      author: 'Delilah S. Dawson',
      ageRange: AGES,
    },
    {
      id: 'sonic-the-hedgehog-battle-for',
      coverId: 12884582,
      title: 'Sonic the Hedgehog: Battle for the Empire',
      author: 'Ian Flynn',
      ageRange: AGES,
    },
  ],
  'Social Issues/Realistic Fiction': [
    {
      id: 'save-me-a-seat',
      coverId: 8895051,
      title: 'Save Me a Seat',
      author: 'Sarah Weeks',
      ageRange: AGES,
    },
    {
      id: 'a-good-kind-of-trouble',
      coverId: 14559622,
      title: 'A Good Kind of Trouble',
      author: 'Lisa Moore Ramee',
      ageRange: AGES,
    },
    {
      id: 'other-words-for-home',
      coverId: 8737138,
      title: 'Other Words for Home',
      author: 'Jasmine Warga',
      ageRange: AGES,
    },
    {
      id: 'amal-unbound',
      coverId: 9362456,
      title: 'Amal Unbound',
      author: 'Aisha Saeed',
      ageRange: AGES,
    },
    {
      id: 'each-kindness',
      coverId: 7271312,
      title: 'Each Kindness',
      author: 'Jacqueline Woodson',
      ageRange: AGES,
    },
    {
      id: 'insignificant-events-in-the-life',
      coverId: 9256276,
      title: 'Insignificant Events in the Life of a Cactus',
      author: 'Dusti Bowling',
      ageRange: AGES,
    },
    {
      id: 'merci-suarez-changes-gears',
      coverId: 9312852,
      title: 'Merci Suarez Changes Gears',
      author: 'Meg Medina',
      ageRange: AGES,
    },
    {
      id: 'the-only-road',
      coverId: 12627124,
      title: 'The Only Road',
      author: 'Alexandra Diaz',
      ageRange: AGES,
    },
    {
      id: 'ghost-boys',
      coverId: 10622842,
      title: 'Ghost Boys',
      author: 'Jewell Parker Rhodes',
      ageRange: AGES,
    },
    {
      id: 'harbor-me',
      coverId: 8824654,
      title: 'Harbor Me',
      author: 'Jacqueline Woodson',
      ageRange: AGES,
    },
    {
      id: 'new-from-here',
      coverId: 12430361,
      title: 'New From Here',
      author: 'Kelly Yang',
      ageRange: AGES,
    },
    {
      id: 'efren-divided',
      coverId: 10660748,
      title: 'Efren Divided',
      author: 'Ernesto Cisneros',
      ageRange: AGES,
    },
    {
      id: 'blended',
      coverId: 12366755,
      title: 'Blended',
      author: 'Sharon M. Draper',
      ageRange: AGES,
    },
    {
      id: 'front-desk',
      coverId: 8803949,
      title: 'Front Desk',
      author: 'Kelly Yang',
      ageRange: AGES,
    },
  ],
  'Animal Rescue/Nature Books': [
    {
      id: 'shiloh',
      coverId: 10275959,
      title: 'Shiloh',
      author: 'Phyllis Reynolds Naylor',
      ageRange: AGES,
    },
    {
      id: 'a-dogs-life-the-autobiography',
      coverId: 279117,
      title: "A Dog's Life: The Autobiography of a Stray",
      author: 'Ann M. Martin',
      ageRange: AGES,
    },
    {
      id: 'the-incredible-journey',
      coverId: 14539398,
      title: 'The Incredible Journey',
      author: 'Sheila Burnford',
      ageRange: AGES,
    },
    { id: 'hoot', coverId: 9320679, title: 'Hoot', author: 'Carl Hiaasen', ageRange: AGES },
    {
      id: 'mrs-frisby-and-the-rats',
      coverId: 7762286,
      title: 'Mrs. Frisby and the Rats of NIMH',
      author: "Robert C. O'Brien",
      ageRange: AGES,
    },
    {
      id: 'owls-in-the-family',
      coverId: 677706,
      title: 'Owls in the Family',
      author: 'Farley Mowat',
      ageRange: AGES,
    },
    {
      id: 'sadie-and-the-silver-shoes',
      coverId: 9166934,
      title: 'Sadie and the Silver Shoes',
      author: 'Jane Godwin',
      ageRange: AGES,
    },
    {
      id: 'the-trumpet-of-the-swan',
      coverId: 50627,
      title: 'The Trumpet of the Swan',
      author: 'E. B. White',
      ageRange: AGES,
    },
    { id: 'wish', coverId: 14859993, title: 'Wish', author: "Barbara O'Connor", ageRange: AGES },
    {
      id: 'the-one-and-only-bob',
      coverId: 10108500,
      title: 'The One and Only Bob',
      author: 'Katherine Applegate',
      ageRange: AGES,
    },
    {
      id: 'bunnicula',
      coverId: 8536550,
      title: 'Bunnicula',
      author: 'Deborah Howe',
      ageRange: AGES,
    },
    {
      id: 'love-that-dog',
      coverId: 3240524,
      title: 'Love That Dog',
      author: 'Sharon Creech',
      ageRange: AGES,
    },
    {
      id: 'rescue',
      coverId: 12723007,
      title: 'Rescue',
      author: 'Jennifer A. Nielsen',
      ageRange: AGES,
    },
    {
      id: 'the-miraculous-journey-of-edward',
      coverId: 3326249,
      title: 'The Miraculous Journey of Edward Tulane',
      author: 'Kate DiCamillo',
      ageRange: AGES,
    },
  ],
  'Historical Fiction (Civil Rights)': [
    {
      id: 'roll-of-thunder-hear-my',
      coverId: 12632397,
      title: 'Roll of Thunder, Hear My Cry',
      author: 'Mildred D. Taylor',
      ageRange: AGES,
    },
    {
      id: 'the-watsons-go-to-birmingham',
      coverId: 10323552,
      title: 'The Watsons Go to Birmingham - 1963',
      author: 'Christopher Paul Curtis',
      ageRange: AGES,
    },
    {
      id: 'one-crazy-summer',
      coverId: 10134796,
      title: 'One Crazy Summer',
      author: 'Rita Williams-Garcia',
      ageRange: AGES,
    },
    {
      id: 'freedom-summer',
      coverId: 439110,
      title: 'Freedom Summer',
      author: 'Deborah Wiles',
      ageRange: AGES,
    },
    {
      id: 'ruth-and-the-green-book',
      coverId: 13771738,
      title: 'Ruth and the Green Book',
      author: 'Calvin Alexander Ramsey',
      ageRange: AGES,
    },
    {
      id: 'the-lions-of-little-rock',
      coverId: 8371385,
      title: 'The Lions of Little Rock',
      author: 'Kristin Levine',
      ageRange: AGES,
    },
    {
      id: 'stella-by-starlight',
      coverId: 10848406,
      title: 'Stella by Starlight',
      author: 'Sharon M. Draper',
      ageRange: AGES,
    },
    {
      id: 'midnight-without-a-moon',
      coverId: 8861896,
      title: 'Midnight Without a Moon',
      author: 'Linda Williams Jackson',
      ageRange: AGES,
    },
    {
      id: 'revolution',
      coverId: 9441532,
      title: 'Revolution',
      author: 'Deborah Wiles',
      ageRange: AGES,
    },
    {
      id: 'p-s-be-eleven',
      coverId: 10134810,
      title: 'P.S. Be Eleven',
      author: 'Rita Williams-Garcia',
      ageRange: AGES,
    },
    {
      id: 'the-rock-and-the-river',
      coverId: 6670012,
      title: 'The Rock and the River',
      author: 'Kekla Magoon',
      ageRange: AGES,
    },
    {
      id: 'gone-crazy-in-alabama',
      coverId: 10696124,
      title: 'Gone Crazy in Alabama',
      author: 'Rita Williams-Garcia',
      ageRange: AGES,
    },
    {
      id: 'sit-in-how-four-friends',
      coverId: 6666599,
      title: 'Sit-In: How Four Friends Stood Up by Sitting Down',
      author: 'Andrea Davis Pinkney',
      ageRange: AGES,
    },
    {
      id: 'finding-langston',
      coverId: 13153194,
      title: 'Finding Langston',
      author: 'Lesa Cline-Ransome',
      ageRange: AGES,
    },
  ],
  'Short Story Collections': [
    {
      id: 'flying-lessons-other-stories',
      coverId: 14598089,
      title: 'Flying Lessons & Other Stories',
      author: 'Ellen Oh',
      ageRange: AGES,
    },
    {
      id: 'the-stories-julian-tells',
      coverId: 254718,
      title: 'The Stories Julian Tells',
      author: 'Ann Cameron',
      ageRange: AGES,
    },
    {
      id: 'scary-stories-to-tell-in',
      coverId: 12634210,
      title: 'Scary Stories to Tell in the Dark',
      author: 'Alvin Schwartz',
      ageRange: AGES,
    },
    {
      id: 'the-people-could-fly-american',
      coverId: 234331,
      title: 'The People Could Fly: American Black Folktales',
      author: 'Virginia Hamilton',
      ageRange: AGES,
    },
    {
      id: 'guys-read-other-worlds',
      coverId: 7684137,
      title: 'Guys Read: Other Worlds',
      author: 'Jon Scieszka',
      ageRange: AGES,
    },
    {
      id: 'aint-burned-all-the-bright',
      coverId: 12535774,
      title: "Ain't Burned All the Bright",
      author: 'Jason Reynolds',
      ageRange: AGES,
    },
    {
      id: 'guys-read-thriller',
      coverId: 12564939,
      title: 'Guys Read: Thriller',
      author: 'Jon Scieszka',
      ageRange: AGES,
    },
    {
      id: 'the-hero-next-door',
      coverId: 8769426,
      title: 'The Hero Next Door',
      author: 'Olugbemisola Rhuday-Perkovich',
      ageRange: AGES,
    },
    {
      id: 'once-upon-an-eid',
      coverId: 9927504,
      title: 'Once Upon an Eid',
      author: 'S. K. Ali',
      ageRange: AGES,
    },
    {
      id: 'ancestor-approved',
      coverId: 15090379,
      title: 'Ancestor Approved',
      author: 'Cynthia Leitich Smith',
      ageRange: AGES,
    },
    {
      id: 'more-scary-stories-to-tell',
      coverId: 12634238,
      title: 'More Scary Stories to Tell in the Dark',
      author: 'Alvin Schwartz',
      ageRange: AGES,
    },
    {
      id: 'scary-stories-3',
      coverId: 12634239,
      title: 'Scary Stories 3',
      author: 'Alvin Schwartz',
      ageRange: AGES,
    },
    {
      id: 'funny-girl',
      coverId: 8814840,
      title: 'Funny Girl',
      author: 'Betsy Bird',
      ageRange: AGES,
    },
  ],
  'Hi-Lo Books (High Interest, Low Readability)': [
    {
      id: 'i-survived-the-shark-attacks',
      coverId: 7239957,
      title: 'I Survived the Shark Attacks of 1916',
      author: 'Lauren Tarshis',
      ageRange: AGES,
    },
    {
      id: 'the-bad-guys-in-mission',
      coverId: 7905630,
      title: 'The Bad Guys in Mission Unpluckable',
      author: 'Aaron Blabey',
      ageRange: AGES,
    },
    { id: 'stick-dog', coverId: 7393614, title: 'Stick Dog', author: 'Tom Watson', ageRange: AGES },
    {
      id: 'ricky-ricottas-mighty-robot',
      coverId: 1229405,
      title: "Ricky Ricotta's Mighty Robot",
      author: 'Dav Pilkey',
      ageRange: AGES,
    },
    {
      id: 'jake-drake-bully-buster',
      coverId: 4289205,
      title: 'Jake Drake, Bully Buster',
      author: 'Andrew Clements',
      ageRange: AGES,
    },
    {
      id: 'press-start-game-over-super',
      coverId: 10151893,
      title: 'Press Start! Game Over, Super Rabbit Boy!',
      author: 'Thomas Flintham',
      ageRange: AGES,
    },
    {
      id: 'i-survived-the-destruction-of',
      coverId: 7346359,
      title: 'I Survived the Destruction of Pompeii, AD 79',
      author: 'Lauren Tarshis',
      ageRange: AGES,
    },
    {
      id: 'i-survived-hurricane-katrina-2005',
      coverId: 6747109,
      title: 'I Survived Hurricane Katrina, 2005',
      author: 'Lauren Tarshis',
      ageRange: AGES,
    },
    {
      id: 'rise-of-the-earth-dragon',
      coverId: 10458783,
      title: 'Rise of the Earth Dragon',
      author: 'Tracey West',
      ageRange: AGES,
    },
    {
      id: 'evas-treetop-festival',
      coverId: 7909390,
      title: "Eva's Treetop Festival",
      author: 'Rebecca Elliott',
      ageRange: AGES,
    },
    {
      id: 'stick-dog-wants-a-hot',
      coverId: 11307933,
      title: 'Stick Dog Wants a Hot Dog',
      author: 'Tom Watson',
      ageRange: AGES,
    },
    {
      id: 'lets-get-cracking',
      coverId: 7884200,
      title: "Let's Get Cracking!",
      author: 'Cyndi Marko',
      ageRange: AGES,
    },
    {
      id: 'the-haunted-house-next-door',
      coverId: 9788904,
      title: 'The Haunted House Next Door',
      author: 'Andres Miedoso',
      ageRange: AGES,
    },
  ],
  'Graphic Novels': [
    {
      id: 'the-cardboard-kingdom',
      coverId: 11159217,
      title: 'The Cardboard Kingdom',
      author: 'Chad Sell',
      ageRange: AGES,
    },
    { id: 'guts', coverId: 8788696, title: 'Guts', author: 'Raina Telgemeier', ageRange: AGES },
    { id: 'drama', coverId: 12360868, title: 'Drama', author: 'Raina Telgemeier', ageRange: AGES },
    {
      id: 'real-friends',
      coverId: 9322318,
      title: 'Real Friends',
      author: 'Shannon Hale',
      ageRange: AGES,
    },
    { id: 'click', coverId: 8796431, title: 'Click', author: 'Kayla Miller', ageRange: AGES },
    {
      id: 'narwhal-unicorn-of-the-sea',
      coverId: 7899096,
      title: 'Narwhal: Unicorn of the Sea',
      author: 'Ben Clanton',
      ageRange: AGES,
    },
    {
      id: 'mighty-jack',
      coverId: 14496747,
      title: 'Mighty Jack',
      author: 'Ben Hatke',
      ageRange: AGES,
    },
    { id: 'stargazing', coverId: 9120286, title: 'Stargazing', author: 'Jen Wang', ageRange: AGES },
    {
      id: 'sisters',
      coverId: 7370154,
      title: 'Sisters',
      author: 'Raina Telgemeier',
      ageRange: AGES,
    },
    { id: 'camp', coverId: 8988976, title: 'Camp', author: 'Kayla Miller', ageRange: AGES },
    {
      id: 'best-friends',
      coverId: 8771908,
      title: 'Best Friends',
      author: 'Shannon Hale',
      ageRange: AGES,
    },
    { id: 'pawcasso', coverId: 11166070, title: 'Pawcasso', author: 'Remy Lai', ageRange: AGES },
    {
      id: 'squished',
      coverId: 13268437,
      title: 'Squished',
      author: 'Megan Wagner Lloyd',
      ageRange: AGES,
    },
    {
      id: 'doodleville',
      coverId: 10443681,
      title: 'Doodleville',
      author: 'Chad Sell',
      ageRange: AGES,
    },
  ],
  'Trending/New Releases': [
    {
      id: 'the-eyes-and-the-impossible',
      coverId: 14731454,
      title: 'The Eyes and the Impossible',
      author: 'Dave Eggers',
      ageRange: AGES,
    },
    {
      id: 'freewater',
      coverId: 13196433,
      title: 'Freewater',
      author: 'Amina Luqman-Dawson',
      ageRange: AGES,
    },
    {
      id: 'the-last-mapmaker',
      coverId: 12716142,
      title: 'The Last Mapmaker',
      author: 'Christina Soontornvat',
      ageRange: AGES,
    },
    {
      id: 'when-you-trap-a-tiger',
      coverId: 9256649,
      title: 'When You Trap a Tiger',
      author: 'Tae Keller',
      ageRange: AGES,
    },
    {
      id: 'the-first-state-of-being',
      coverId: 14590766,
      title: 'The First State of Being',
      author: 'Erin Entrada Kelly',
      ageRange: AGES,
    },
    {
      id: 'simon-sort-of-says',
      coverId: 13185788,
      title: 'Simon Sort of Says',
      author: 'Erin Bow',
      ageRange: AGES,
    },
    {
      id: 'the-lost-year',
      coverId: 13141079,
      title: 'The Lost Year',
      author: 'Katherine Marsh',
      ageRange: AGES,
    },
    {
      id: 'the-many-assassinations-of-samir',
      coverId: 13441449,
      title: 'The Many Assassinations of Samir, the Seller of Dreams',
      author: 'Daniel Nayeri',
      ageRange: AGES,
    },
    {
      id: 'iveliz-explains-it-all',
      coverId: 12619950,
      title: 'Iveliz Explains It All',
      author: 'Andrea Beatriz Arango',
      ageRange: AGES,
    },
    { id: 'mexikid', coverId: 14399136, title: 'Mexikid', author: 'Pedro Martin', ageRange: AGES },
    {
      id: 'big-tree',
      coverId: 13470352,
      title: 'Big Tree',
      author: 'Brian Selznick',
      ageRange: AGES,
    },
    { id: 'ferris', coverId: 14562109, title: 'Ferris', author: 'Kate DiCamillo', ageRange: AGES },
    {
      id: 'the-sherlock-society',
      coverId: 14815052,
      title: 'The Sherlock Society',
      author: 'James Ponti',
      ageRange: AGES,
    },
  ],
  'Books with Movie/TV Adaptations': [
    {
      id: 'charlie-and-the-chocolate-factory',
      coverId: 12459564,
      title: 'Charlie and the Chocolate Factory',
      author: 'Roald Dahl',
      ageRange: AGES,
    },
    {
      id: 'how-to-train-your-dragon',
      coverId: 190086,
      title: 'How to Train Your Dragon',
      author: 'Cressida Cowell',
      ageRange: AGES,
    },
    {
      id: 'the-spiderwick-chronicles-the-field',
      coverId: 13772765,
      title: 'The Spiderwick Chronicles: The Field Guide',
      author: 'Tony DiTerlizzi',
      ageRange: AGES,
    },
    { id: 'coraline', coverId: 14171421, title: 'Coraline', author: 'Neil Gaiman', ageRange: AGES },
    { id: 'the-bfg', coverId: 9176033, title: 'The BFG', author: 'Roald Dahl', ageRange: AGES },
    {
      id: 'stuart-little',
      coverId: 10522876,
      title: 'Stuart Little',
      author: 'E. B. White',
      ageRange: AGES,
    },
    {
      id: 'james-and-the-giant-peach',
      coverId: 8252454,
      title: 'James and the Giant Peach',
      author: 'Roald Dahl',
      ageRange: AGES,
    },
    {
      id: 'the-indian-in-the-cupboard',
      coverId: 6961353,
      title: 'The Indian in the Cupboard',
      author: 'Lynne Reid Banks',
      ageRange: AGES,
    },
    {
      id: 'the-witches',
      coverId: 12374442,
      title: 'The Witches',
      author: 'Roald Dahl',
      ageRange: AGES,
    },
    {
      id: 'fantastic-mr-fox',
      coverId: 6498519,
      title: 'Fantastic Mr. Fox',
      author: 'Roald Dahl',
      ageRange: AGES,
    },
    {
      id: 'ella-enchanted',
      coverId: 50323,
      title: 'Ella Enchanted',
      author: 'Gail Carson Levine',
      ageRange: AGES,
    },
    {
      id: 'the-secret-garden',
      coverId: 12622062,
      title: 'The Secret Garden',
      author: 'Frances Hodgson Burnett',
      ageRange: AGES,
    },
    {
      id: 'harriet-the-spy',
      coverId: 12569145,
      title: 'Harriet the Spy',
      author: 'Louise Fitzhugh',
      ageRange: AGES,
    },
    {
      id: 'mr-poppers-penguins',
      coverId: 187773,
      title: "Mr. Popper's Penguins",
      author: 'Richard Atwater',
      ageRange: AGES,
    },
  ],
  'School/Social Dynamics Fiction': [
    {
      id: 'frindle',
      coverId: 9265167,
      title: 'Frindle',
      author: 'Andrew Clements',
      ageRange: AGES,
    },
    { id: 'loser', coverId: 8261207, title: 'Loser', author: 'Jerry Spinelli', ageRange: AGES },
    {
      id: 'dork-diaries-tales-from-a',
      coverId: 10522790,
      title: 'Dork Diaries: Tales from a Not-So-Fabulous Life',
      author: 'Rachel Renee Russell',
      ageRange: AGES,
    },
    { id: 'restart', coverId: 8573234, title: 'Restart', author: 'Gordon Korman', ageRange: AGES },
    {
      id: 'ungifted',
      coverId: 7263528,
      title: 'Ungifted',
      author: 'Gordon Korman',
      ageRange: AGES,
    },
    {
      id: 'the-report-card',
      coverId: 1472164,
      title: 'The Report Card',
      author: 'Andrew Clements',
      ageRange: AGES,
    },
    {
      id: 'posted',
      coverId: 8814792,
      title: 'Posted',
      author: 'John David Anderson',
      ageRange: AGES,
    },
    {
      id: 'schooled',
      coverId: 9069479,
      title: 'Schooled',
      author: 'Gordon Korman',
      ageRange: AGES,
    },
    {
      id: 'no-talking',
      coverId: 481392,
      title: 'No Talking',
      author: 'Andrew Clements',
      ageRange: AGES,
    },
    {
      id: 'lunch-money',
      coverId: 438348,
      title: 'Lunch Money',
      author: 'Andrew Clements',
      ageRange: AGES,
    },
    { id: 'slacker', coverId: 8170851, title: 'Slacker', author: 'Gordon Korman', ageRange: AGES },
    {
      id: 'the-miscalculations-of-lightning-girl',
      coverId: 15090612,
      title: 'The Miscalculations of Lightning Girl',
      author: 'Stacy McAnulty',
      ageRange: AGES,
    },
    {
      id: 'better-nate-than-ever',
      coverId: 8995578,
      title: 'Better Nate Than Ever',
      author: 'Tim Federle',
      ageRange: AGES,
    },
    {
      id: 'fourth-grade-rats',
      coverId: 14860065,
      title: 'Fourth Grade Rats',
      author: 'Jerry Spinelli',
      ageRange: AGES,
    },
  ],
  'Informational Texts/Encyclopedias': [
    {
      id: 'national-geographic-kids-almanac',
      coverId: 11302225,
      title: 'National Geographic Kids Almanac',
      author: 'National Geographic Kids',
      ageRange: AGES,
    },
    {
      id: 'the-way-things-work-now',
      coverId: 257822,
      title: 'The Way Things Work Now',
      author: 'David Macaulay',
      ageRange: AGES,
    },
    {
      id: 'guinness-world-records',
      coverId: 4636740,
      title: 'Guinness World Records',
      author: 'Guinness World Records',
      ageRange: AGES,
    },
    {
      id: 'everything-you-need-to-ace',
      coverId: 10318264,
      title: 'Everything You Need to Ace Science in One Big Fat Notebook',
      author: 'Workman Publishing',
      ageRange: AGES,
    },
    {
      id: 'dk-eyewitness-books-ancient-rome',
      coverId: 13762222,
      title: 'DK Eyewitness Books: Ancient Rome',
      author: 'Simon James',
      ageRange: AGES,
    },
    {
      id: 'national-geographic-kids-why',
      coverId: 8842305,
      title: 'National Geographic Kids Why?',
      author: 'Crispin Boyer',
      ageRange: AGES,
    },
    {
      id: 'weird-but-true',
      coverId: 9467664,
      title: 'Weird But True!',
      author: 'National Geographic Kids',
      ageRange: AGES,
    },
    {
      id: '5-000-awesome-facts-about',
      coverId: 14423688,
      title: '5,000 Awesome Facts About Everything',
      author: 'National Geographic Kids',
      ageRange: AGES,
    },
    {
      id: 'eyewitness-dinosaur',
      coverId: 4249596,
      title: 'Eyewitness Dinosaur',
      author: 'David Lambert',
      ageRange: AGES,
    },
    {
      id: 'ripleys-believe-it-or-not',
      coverId: 8124831,
      title: "Ripley's Believe It or Not!",
      author: 'Ripley Entertainment',
      ageRange: AGES,
    },
    {
      id: 'eyewitness-shark',
      coverId: 423802,
      title: 'Eyewitness Shark',
      author: 'Miranda MacQuitty',
      ageRange: AGES,
    },
    {
      id: 'encyclopedia-prehistorica-dinosaurs',
      coverId: 4710183,
      title: 'Encyclopedia Prehistorica Dinosaurs',
      author: 'Robert Sabuda',
      ageRange: AGES,
    },
    {
      id: 'ultimate-weird-but-true',
      coverId: 8969101,
      title: 'Ultimate Weird But True',
      author: 'National Geographic Kids',
      ageRange: AGES,
    },
    {
      id: 'eyewitness-knight',
      coverId: 2996810,
      title: 'Eyewitness Knight',
      author: 'Christopher Gravett',
      ageRange: AGES,
    },
    {
      id: 'the-everything-kids-science-experiments',
      coverId: 840666,
      title: "The Everything Kids' Science Experiments Book",
      author: 'Tom Robinson',
      ageRange: AGES,
    },
  ],
  'STEM Deep-Dives': [
    {
      id: 'older-than-dirt-a-wild',
      coverId: 10228557,
      title: 'Older Than Dirt: A Wild but True History of Earth',
      author: 'Don Brown',
      ageRange: AGES,
    },
    {
      id: 'women-in-science-50-fearless',
      coverId: 13090465,
      title: 'Women in Science: 50 Fearless Pioneers Who Changed the World',
      author: 'Rachel Ignotofsky',
      ageRange: AGES,
    },
    {
      id: 'the-elements-a-visual-exploration',
      coverId: 6374140,
      title: 'The Elements: A Visual Exploration of Every Known Atom in the Universe',
      author: 'Theodore Gray',
      ageRange: AGES,
    },
    {
      id: 'hidden-figures-the-true-story',
      coverId: 10661694,
      title: 'Hidden Figures: The True Story of Four Black Women and the Space Race',
      author: 'Margot Lee Shetterly',
      ageRange: AGES,
    },
    {
      id: 'dinosaurs-the-grand-tour',
      coverId: 8883147,
      title: 'Dinosaurs: The Grand Tour',
      author: 'Keiron Pim',
      ageRange: AGES,
    },
    {
      id: 'grand-canyon',
      coverId: 8155954,
      title: 'Grand Canyon',
      author: 'Jason Chin',
      ageRange: AGES,
    },
    {
      id: 'astrophysics-for-young-people-in',
      coverId: 7984709,
      title: 'Astrophysics for Young People in a Hurry',
      author: 'Neil deGrasse Tyson',
      ageRange: AGES,
    },
    {
      id: 'the-boy-who-loved-math',
      coverId: 7413693,
      title: 'The Boy Who Loved Math',
      author: 'Deborah Heiligman',
      ageRange: AGES,
    },
    {
      id: 'moonshot-the-flight-of-apollo',
      coverId: 10080038,
      title: 'Moonshot: The Flight of Apollo 11',
      author: 'Brian Floca',
      ageRange: AGES,
    },
    {
      id: 'bones-skeletons-and-how-they',
      coverId: 6670318,
      title: 'Bones: Skeletons and How They Work',
      author: 'Steve Jenkins',
      ageRange: AGES,
    },
    {
      id: 'insect-superpowers',
      coverId: 14746684,
      title: 'Insect Superpowers',
      author: 'Kate Messner',
      ageRange: AGES,
    },
    {
      id: 'your-place-in-the-universe',
      coverId: 10454300,
      title: 'Your Place in the Universe',
      author: 'Jason Chin',
      ageRange: AGES,
    },
    {
      id: 'mario-and-the-hole-in',
      coverId: 13976078,
      title: 'Mario and the Hole in the Sky',
      author: 'Elizabeth Rusch',
      ageRange: AGES,
    },
  ],
  'Highly Accurate Historical Fiction': [
    {
      id: 'the-devils-arithmetic',
      coverId: 948682,
      title: "The Devil's Arithmetic",
      author: 'Jane Yolen',
      ageRange: AGES,
    },
    {
      id: 'lyddie',
      coverId: 8013746,
      title: 'Lyddie',
      author: 'Katherine Paterson',
      ageRange: AGES,
    },
    {
      id: 'fever-1793',
      coverId: 436045,
      title: 'Fever 1793',
      author: 'Laurie Halse Anderson',
      ageRange: AGES,
    },
    {
      id: 'the-witch-of-blackbird-pond',
      coverId: 4904594,
      title: 'The Witch of Blackbird Pond',
      author: 'Elizabeth George Speare',
      ageRange: AGES,
    },
    {
      id: 'johnny-tremain',
      coverId: 282869,
      title: 'Johnny Tremain',
      author: 'Esther Forbes',
      ageRange: AGES,
    },
    {
      id: 'under-the-blood-red-sun',
      coverId: 371438,
      title: 'Under the Blood-Red Sun',
      author: 'Graham Salisbury',
      ageRange: AGES,
    },
    {
      id: 'crispin-the-cross-of-lead',
      coverId: 11152338,
      title: 'Crispin: The Cross of Lead',
      author: 'Avi',
      ageRange: AGES,
    },
    {
      id: 'a-single-shard',
      coverId: 6245993,
      title: 'A Single Shard',
      author: 'Linda Sue Park',
      ageRange: AGES,
    },
    {
      id: 'the-midwifes-apprentice',
      coverId: 256426,
      title: "The Midwife's Apprentice",
      author: 'Karen Cushman',
      ageRange: AGES,
    },
    {
      id: 'bull-run',
      coverId: 3997031,
      title: 'Bull Run',
      author: 'Paul Fleischman',
      ageRange: AGES,
    },
    {
      id: 'nory-ryans-song',
      coverId: 239319,
      title: "Nory Ryan's Song",
      author: 'Patricia Reilly Giff',
      ageRange: AGES,
    },
    {
      id: 'out-of-the-dust',
      coverId: 4977479,
      title: 'Out of the Dust',
      author: 'Karen Hesse',
      ageRange: AGES,
    },
    { id: 'dash', coverId: 7320534, title: 'Dash', author: 'Kirby Larson', ageRange: AGES },
    {
      id: 'catherine-called-birdy',
      coverId: 1466478,
      title: 'Catherine, Called Birdy',
      author: 'Karen Cushman',
      ageRange: AGES,
    },
  ],
  'Friendship/School Stories': [
    {
      id: 'the-year-of-billy-miller',
      coverId: 7358098,
      title: 'The Year of Billy Miller',
      author: 'Kevin Henkes',
      ageRange: AGES,
    },
    {
      id: 'ivy-and-bean',
      coverId: 14859219,
      title: 'Ivy and Bean',
      author: 'Annie Barrows',
      ageRange: AGES,
    },
    {
      id: 'clementine',
      coverId: 7368598,
      title: 'Clementine',
      author: 'Sara Pennypacker',
      ageRange: AGES,
    },
    {
      id: 'ramona-quimby-age-8',
      coverId: 15064600,
      title: 'Ramona Quimby, Age 8',
      author: 'Beverly Cleary',
      ageRange: AGES,
    },
    {
      id: 'the-best-christmas-pageant-ever',
      coverId: 50055,
      title: 'The Best Christmas Pageant Ever',
      author: 'Barbara Robinson',
      ageRange: AGES,
    },
    {
      id: 'the-great-gilly-hopkins',
      coverId: 2292779,
      title: 'The Great Gilly Hopkins',
      author: 'Katherine Paterson',
      ageRange: AGES,
    },
    {
      id: 'stargirl',
      coverId: 14860109,
      title: 'Stargirl',
      author: 'Jerry Spinelli',
      ageRange: AGES,
    },
    {
      id: 'the-wild-book',
      coverId: 9463092,
      title: 'The Wild Book',
      author: 'Margarita Engle',
      ageRange: AGES,
    },
    { id: 'rules', coverId: 277888, title: 'Rules', author: 'Cynthia Lord', ageRange: AGES },
    {
      id: 'aminas-voice',
      coverId: 10836814,
      title: "Amina's Voice",
      author: 'Hena Khan',
      ageRange: AGES,
    },
    {
      id: 'song-for-a-whale',
      coverId: 8807091,
      title: 'Song for a Whale',
      author: 'Lynne Kelly',
      ageRange: AGES,
    },
    {
      id: 'because-of-the-rabbit',
      coverId: 8795421,
      title: 'Because of the Rabbit',
      author: 'Cynthia Lord',
      ageRange: AGES,
    },
    {
      id: 'ways-to-make-sunshine',
      coverId: 9358468,
      title: 'Ways to Make Sunshine',
      author: 'Renee Watson',
      ageRange: AGES,
    },
    {
      id: 'the-year-of-the-dog',
      coverId: 8310348,
      title: 'The Year of the Dog',
      author: 'Grace Lin',
      ageRange: AGES,
    },
  ],
  'Humor/Diary-Format Books': [
    {
      id: 'timmy-failure-mistakes-were-made',
      coverId: 7389796,
      title: 'Timmy Failure: Mistakes Were Made',
      author: 'Stephan Pastis',
      ageRange: AGES,
    },
    {
      id: 'my-weird-school-miss-daisy',
      coverId: 14497304,
      title: 'My Weird School: Miss Daisy Is Crazy!',
      author: 'Dan Gutman',
      ageRange: AGES,
    },
    {
      id: 'the-terrible-two',
      coverId: 9541314,
      title: 'The Terrible Two',
      author: 'Mac Barnett',
      ageRange: AGES,
    },
    {
      id: 'the-adventures-of-captain-underpants',
      coverId: 12625278,
      title: 'The Adventures of Captain Underpants',
      author: 'Dav Pilkey',
      ageRange: AGES,
    },
    {
      id: 'middle-school-the-worst-years',
      coverId: 6784984,
      title: 'Middle School: The Worst Years of My Life',
      author: 'James Patterson',
      ageRange: AGES,
    },
    {
      id: 'sideways-stories-from-wayside-school',
      coverId: 6746131,
      title: 'Sideways Stories from Wayside School',
      author: 'Louis Sachar',
      ageRange: AGES,
    },
    {
      id: 'how-to-eat-fried-worms',
      coverId: 14228597,
      title: 'How to Eat Fried Worms',
      author: 'Thomas Rockwell',
      ageRange: AGES,
    },
    {
      id: 'diary-of-a-wimpy-kidx',
      coverId: 8542270,
      title: 'Diary of a Wimpy Kid: Rodrick Rules',
      author: 'Jeff Kinney',
      ageRange: AGES,
    },
    {
      id: 'the-last-straw',
      coverId: 12685121,
      title: 'The Last Straw',
      author: 'Jeff Kinney',
      ageRange: AGES,
    },
    {
      id: 'big-nate-strikes-again',
      coverId: 6626651,
      title: 'Big Nate Strikes Again',
      author: 'Lincoln Peirce',
      ageRange: AGES,
    },
    {
      id: 'now-look-what-youve-done',
      coverId: 10318749,
      title: "Now Look What You've Done",
      author: 'Stephan Pastis',
      ageRange: AGES,
    },
    {
      id: 'the-terrible-two-get-worse',
      coverId: 7423004,
      title: 'The Terrible Two Get Worse',
      author: 'Mac Barnett',
      ageRange: AGES,
    },
    {
      id: 'lets-pretend-this-never-happened',
      coverId: 1278736,
      title: "Let's Pretend This Never Happened",
      author: 'Jim Benton',
      ageRange: AGES,
    },
    {
      id: 'tales-of-a-fourth-grade',
      coverId: 9268263,
      title: 'Tales of a Fourth Grade Nothing',
      author: 'Judy Blume',
      ageRange: AGES,
    },
  ],
  'Lighthearted Contemporary Fiction': [
    {
      id: 'the-vanderbeekers-of-141st-street',
      coverId: 14428878,
      title: 'The Vanderbeekers of 141st Street',
      author: 'Karina Yan Glaser',
      ageRange: AGES,
    },
    {
      id: 'absolutely-almost',
      coverId: 7306850,
      title: 'Absolutely Almost',
      author: 'Lisa Graff',
      ageRange: AGES,
    },
    {
      id: 'the-penderwicks',
      coverId: 12715723,
      title: 'The Penderwicks',
      author: 'Jeanne Birdsall',
      ageRange: AGES,
    },
    {
      id: 'ellie-engineer',
      coverId: 8833235,
      title: 'Ellie, Engineer',
      author: 'Jackson Pearce',
      ageRange: AGES,
    },
    {
      id: 'a-boy-called-bat',
      coverId: 8814296,
      title: 'A Boy Called Bat',
      author: 'Elana K. Arnold',
      ageRange: AGES,
    },
    {
      id: 'stef-soto-taco-queen',
      coverId: 9339076,
      title: 'Stef Soto, Taco Queen',
      author: 'Jennifer Torres',
      ageRange: AGES,
    },
    {
      id: 'the-popularity-papers',
      coverId: 7090677,
      title: 'The Popularity Papers',
      author: 'Amy Ignatow',
      ageRange: AGES,
    },
    {
      id: 'front-desk-three-keys',
      coverId: 10608520,
      title: 'Front Desk: Three Keys',
      author: 'Kelly Yang',
      ageRange: AGES,
    },
    {
      id: 'the-vanderbeekers-and-the-hidden',
      coverId: 8842380,
      title: 'The Vanderbeekers and the Hidden Garden',
      author: 'Karina Yan Glaser',
      ageRange: AGES,
    },
    {
      id: 'roll-with-it',
      coverId: 10318230,
      title: 'Roll with It',
      author: 'Jamie Sumner',
      ageRange: AGES,
    },
    {
      id: 'the-total-eclipse-of-nestor',
      coverId: 10161898,
      title: 'The Total Eclipse of Nestor Lopez',
      author: 'Adrianna Cuevas',
      ageRange: AGES,
    },
    {
      id: 'dress-coded',
      coverId: 10254311,
      title: 'Dress Coded',
      author: 'Carrie Firestone',
      ageRange: AGES,
    },
    {
      id: 'ways-to-grow-love',
      coverId: 10875795,
      title: 'Ways to Grow Love',
      author: 'Renee Watson',
      ageRange: AGES,
    },
    {
      id: 'sweet-home-alaska',
      coverId: 10221801,
      title: 'Sweet Home Alaska',
      author: 'Carole Estby Dagg',
      ageRange: AGES,
    },
  ],
  'Sports Fiction': [
    { id: 'booked', coverId: 12903111, title: 'Booked', author: 'Kwame Alexander', ageRange: AGES },
    {
      id: 'rebound',
      coverId: 8803990,
      title: 'Rebound',
      author: 'Kwame Alexander',
      ageRange: AGES,
    },
    { id: 'heat', coverId: 260205, title: 'Heat', author: 'Mike Lupica', ageRange: AGES },
    {
      id: 'travel-team',
      coverId: 260114,
      title: 'Travel Team',
      author: 'Mike Lupica',
      ageRange: AGES,
    },
    {
      id: 'the-boy-who-saved-baseball',
      coverId: 259931,
      title: 'The Boy Who Saved Baseball',
      author: 'John H. Ritter',
      ageRange: AGES,
    },
    {
      id: 'nikki-on-the-line',
      coverId: 8804249,
      title: 'Nikki on the Line',
      author: 'Barbara Carroll Roberts',
      ageRange: AGES,
    },
    { id: 'soar', coverId: 8901416, title: 'Soar', author: 'Joan Bauer', ageRange: AGES },
    { id: 'keeper', coverId: 516537, title: 'Keeper', author: 'Mal Peet', ageRange: AGES },
    {
      id: 'fast-pitch',
      coverId: 11984357,
      title: 'Fast Pitch',
      author: 'Nic Stone',
      ageRange: AGES,
    },
    {
      id: 'game-changer',
      coverId: 15155664,
      title: 'Game Changer',
      author: 'Tommy Greenwald',
      ageRange: AGES,
    },
    {
      id: 'baseball-genius',
      coverId: 13337198,
      title: 'Baseball Genius',
      author: 'Tim Green',
      ageRange: AGES,
    },
    {
      id: 'football-genius',
      coverId: 4942498,
      title: 'Football Genius',
      author: 'Tim Green',
      ageRange: AGES,
    },
    {
      id: 'the-big-field',
      coverId: 1199611,
      title: 'The Big Field',
      author: 'Mike Lupica',
      ageRange: AGES,
    },
    {
      id: 'out-of-my-league',
      coverId: 9463359,
      title: 'Out of My League',
      author: 'Dirk Hayhurst',
      ageRange: AGES,
    },
  ],
  'Tournament/Competition Books': [
    {
      id: 'the-great-greene-heist',
      coverId: 8120887,
      title: 'The Great Greene Heist',
      author: 'Varian Johnson',
      ageRange: AGES,
    },
    {
      id: 'masterminds',
      coverId: 7442618,
      title: 'Masterminds',
      author: 'Gordon Korman',
      ageRange: AGES,
    },
    {
      id: 'the-candymakers',
      coverId: 6665961,
      title: 'The Candymakers',
      author: 'Wendy Mass',
      ageRange: AGES,
    },
    {
      id: 'spy-school',
      coverId: 8259640,
      title: 'Spy School',
      author: 'Stuart Gibbs',
      ageRange: AGES,
    },
    {
      id: 'the-iron-trial',
      coverId: 8476280,
      title: 'The Iron Trial',
      author: 'Holly Black',
      ageRange: AGES,
    },
    {
      id: 'gregor-the-overlander',
      coverId: 8345963,
      title: 'Gregor the Overlander',
      author: 'Suzanne Collins',
      ageRange: AGES,
    },
    {
      id: 'the-false-prince',
      coverId: 12817931,
      title: 'The False Prince',
      author: 'Jennifer A. Nielsen',
      ageRange: AGES,
    },
    {
      id: 'the-unteachables',
      coverId: 8797316,
      title: 'The Unteachables',
      author: 'Gordon Korman',
      ageRange: AGES,
    },
    {
      id: 'spy-school-secret-service',
      coverId: 9320630,
      title: 'Spy School Secret Service',
      author: 'Stuart Gibbs',
      ageRange: AGES,
    },
    {
      id: 'charlie-thorne-and-the-last',
      coverId: 9273791,
      title: 'Charlie Thorne and the Last Equation',
      author: 'Stuart Gibbs',
      ageRange: AGES,
    },
    {
      id: 'the-blackthorn-key',
      coverId: 7904767,
      title: 'The Blackthorn Key',
      author: 'Kevin Sands',
      ageRange: AGES,
    },
    {
      id: 'the-great-brain',
      coverId: 6507023,
      title: 'The Great Brain',
      author: 'John D. Fitzgerald',
      ageRange: AGES,
    },
    {
      id: 'the-hidden-oracle',
      coverId: 7442820,
      title: 'The Hidden Oracle',
      author: 'Rick Riordan',
      ageRange: AGES,
    },
    {
      id: 'the-fourth-stall',
      coverId: 6682459,
      title: 'The Fourth Stall',
      author: 'Chris Rylander',
      ageRange: AGES,
    },
  ],
  'Biographies of Athletes/Innovators': [
    {
      id: 'who-was-jackie-robinson',
      coverId: 9148022,
      title: 'Who Was Jackie Robinson?',
      author: 'Gail Herman',
      ageRange: AGES,
    },
    {
      id: 'undefeated-jim-thorpe-and-the',
      coverId: 9257716,
      title: 'Undefeated: Jim Thorpe and the Carlisle Indian School Football Team',
      author: 'Steve Sheinkin',
      ageRange: AGES,
    },
    {
      id: 'who-was-muhammad-ali',
      coverId: 8738100,
      title: 'Who Was Muhammad Ali?',
      author: 'James Buckley Jr.',
      ageRange: AGES,
    },
    {
      id: 'who-was-steve-jobs',
      coverId: 7347489,
      title: 'Who Was Steve Jobs?',
      author: 'Pam Pollack',
      ageRange: AGES,
    },
    {
      id: 'who-is-simone-biles',
      coverId: 14428056,
      title: 'Who Is Simone Biles?',
      author: 'Stefanie Loh',
      ageRange: AGES,
    },
    {
      id: 'salt-in-his-shoes-michael',
      coverId: 435810,
      title: 'Salt in His Shoes: Michael Jordan in Pursuit of a Dream',
      author: 'Deloris Jordan',
      ageRange: AGES,
    },
    {
      id: 'who-was-jesse-owens',
      coverId: 12139565,
      title: 'Who Was Jesse Owens?',
      author: 'James Buckley Jr.',
      ageRange: AGES,
    },
    {
      id: 'who-was-roberto-clemente',
      coverId: 8476199,
      title: 'Who Was Roberto Clemente?',
      author: 'James Buckley Jr.',
      ageRange: AGES,
    },
    {
      id: 'who-was-milton-hershey',
      coverId: 9148012,
      title: 'Who Was Milton Hershey?',
      author: 'James Buckley Jr.',
      ageRange: AGES,
    },
    {
      id: 'who-was-thomas-alva-edison',
      coverId: 289676,
      title: 'Who Was Thomas Alva Edison?',
      author: 'Margaret Frith',
      ageRange: AGES,
    },
    {
      id: 'who-was-marie-curie',
      coverId: 7317233,
      title: 'Who Was Marie Curie?',
      author: 'Megan Stine',
      ageRange: AGES,
    },
    {
      id: 'queen-of-the-track',
      coverId: 9653039,
      title: 'Queen of the Track',
      author: 'Heather Lang',
      ageRange: AGES,
    },
  ],
}
