// ─── Icon ───────────────────────────────────────────────────────────────────
// Single house-styled icon component for the whole prototype system, backed by
// the @tabler/icons-react library (premium, consistent stroke set). Use semantic
// kebab-case names so call sites stay library-agnostic — the registry below is
// the one place that maps a name to a Tabler glyph. Add new icons here.
//
//   import { Icon } from '@components/Icon/Icon'
//   <Icon name="chevron-down" />              // default size 18, stroke 1.8
//   <Icon name="flame" size={20} />
//   <Icon name="flag" size={16} color="#E85648" />
//
// Color: omit `color` to inherit `currentColor` (the usual case). Stroke width
// and size can be overridden per call site.

import './Icon.css'
import {
  // ── navigation / controls ──
  IconChevronDown,
  IconChevronUp,
  IconChevronsDown,
  IconChevronsUp,
  IconChevronLeft,
  IconChevronRight,
  IconArrowRight,
  IconArrowLeft,
  IconArrowUp,
  IconArrowDown,
  IconArrowBackUp,
  IconX,
  IconCheck,
  IconPlugOff,
  IconPlus,
  IconMinus,
  IconDots,
  IconDotsVertical,
  IconGripVertical,
  IconMenu2,
  // ── status / feedback ──
  IconInfoCircle,
  IconBrandFacebook,
  IconBrandX,
  IconBuildingStore,
  IconCircle,
  IconCoin,
  IconCircleCheck,
  IconCircleCheckFilled,
  IconCircleX,
  IconCircleXFilled,
  IconPointFilled,
  IconAlertTriangle,
  IconAlertCircle,
  IconAlertCircleFilled,
  IconHelpCircle,
  // ── reading / domain ──
  IconBook,
  IconBook2,
  IconVocabulary,
  IconBlockquote,
  IconBarcode,
  IconNotebook,
  IconFlame,
  IconFlameFilled,
  IconShield,
  IconShieldCheck,
  IconCalendar,
  IconCalendarEvent,
  IconCalendarStats,
  IconClock,
  IconStopwatch,
  IconHistory,
  IconUser,
  IconUserPlus,
  IconUserOff,
  IconUsers,
  IconFlag,
  IconFlagFilled,
  IconTrophy,
  IconAward,
  IconBadge,
  IconMedal,
  IconCertificate,
  IconGift,
  IconTicket,
  IconQrcode,
  IconPuzzle,
  IconTarget,
  IconStar,
  IconStarFilled,
  IconBolt,
  IconHeart,
  IconHeartFilled,
  IconCrown,
  IconRocket,
  IconLeaf,
  // ── actions ──
  IconSettings,
  IconPencil,
  IconWriting,
  IconCopy,
  IconTrash,
  IconArchive,
  IconLink,
  IconUnlink,
  IconPlugConnected,
  IconEye,
  IconEyeOff,
  IconSearch,
  IconFilter,
  IconDownload,
  IconPrinter,
  IconUpload,
  IconPin,
  IconPinFilled,
  IconSignature,
  // ── content / objects ──
  IconSparkles,
  IconBulb,
  IconSpeakerphone,
  IconSun,
  IconMoon,
  IconMoodSmile,
  IconLock,
  IconMessageCircle,
  IconMessageCircleCheck,
  IconMessageX,
  IconMessages,
  IconMessageChatbot,
  IconMicrophone,
  IconVolume,
  IconVolumeOff,
  IconPlayerStopFilled,
  IconPlayerPlayFilled,
  IconPlayerPauseFilled,
  IconRewindBackward15,
  IconRewindForward15,
  IconConfetti,
  IconApple,
  IconSend,
  IconInbox,
  IconFileText,
  IconClipboardCheck,
  IconClipboardList,
  IconList,
  IconListNumbers,
  IconAlignLeft,
  IconScribble,
  IconWaveSine,
  IconQuote,
  IconCode,
  IconPhoto,
  IconPalette,
  IconZoomIn,
  IconZoomOut,
  // ── layout / structure ──
  IconRoute,
  IconDice5,
  IconLayoutGrid,
  IconLayoutDashboard,
  IconLayout,
  IconLayoutColumns,
  IconLayoutBottombar,
  IconStack2,
  IconAtom,
  IconForms,
  IconBrowser,
  // ── data / analytics ──
  IconChartBar,
  IconChartColumn,
  IconChartLine,
  IconTrendingUp,
  IconReportAnalytics,
  // ── places / sync ──
  IconSchool,
  IconBuilding,
  IconBuildingCommunity,
  IconArrowsExchange,
  IconSwitchHorizontal,
  IconRefresh,
  // ── safety / wellbeing / notifications ──
  IconBell,
  IconBellRinging,
  IconMail,
  IconPhone,
  IconPhoneCall,
  IconLifebuoy,
  IconMoodSad,
  IconMoodCry,
  IconMoodHappy,
  IconMoodNeutral,
  IconHeartHandshake,
  IconShieldHeart,
  IconShieldExclamation,
  IconExternalLink,
  IconMaximize,
  IconBan,
  IconRosetteDiscountCheckFilled,
  IconCircleMinus,
  IconUserUp,
  IconKey,
  IconSquare,
  IconSquareCheckFilled,
  IconHourglass,
  IconId,
  IconMinimize,
  IconHeartbeat,
  IconActivityHeartbeat,
  IconUserShield,
  IconMessageReport,
  IconFirstAidKit,
  IconAlertHexagon,
  // ── book discovery ──
  IconHeadphones,
  IconDeviceDesktop,
  IconDeviceMobile,
  IconDeviceTablet,
  IconMovie,
  IconNews,
  IconBookmark,
  IconBookmarkFilled,
  IconCompass,
  IconThumbUp,
  IconThumbUpFilled,
  IconShare,
  IconChecks,
  // ── pick your path (learning destinations) ──
  IconBallBasketball,
  IconTools,
  IconPaw,
  IconFish,
  IconTrees,
  IconBuildingMonument,
  IconBuildingArch,
  IconGauge,
  IconRuler,
  IconRun,
  IconFlagOff,
  IconSnowflake,
  IconRosetteDiscountCheck,
} from '@tabler/icons-react'

// Semantic name → Tabler component. Keys are kebab-case; a few aliases point at
// the same glyph so call sites can use the most natural word.
const REGISTRY = {
  // navigation / controls
  'chevron-down': IconChevronDown,
  'chevron-up': IconChevronUp,
  'chevrons-down': IconChevronsDown,
  'chevrons-up': IconChevronsUp,
  'chevron-left': IconChevronLeft,
  'chevron-right': IconChevronRight,
  'arrow-right': IconArrowRight,
  'arrow-left': IconArrowLeft,
  'arrow-up': IconArrowUp,
  'arrow-down': IconArrowDown,
  undo: IconArrowBackUp,
  x: IconX,
  close: IconX,
  check: IconCheck,
  plus: IconPlus,
  square: IconSquare,
  'square-check-filled': IconSquareCheckFilled,
  minus: IconMinus,
  dots: IconDots,
  'dots-vertical': IconDotsVertical,
  grip: IconGripVertical,
  menu: IconMenu2,

  // status / feedback
  info: IconInfoCircle,
  'brand-facebook': IconBrandFacebook,
  'brand-x': IconBrandX,
  'building-store': IconBuildingStore,
  circle: IconCircle,
  coin: IconCoin,
  'circle-check': IconCircleCheck,
  'circle-check-filled': IconCircleCheckFilled,
  'circle-x': IconCircleX,
  'circle-x-filled': IconCircleXFilled,
  'point-filled': IconPointFilled,
  'alert-triangle': IconAlertTriangle,
  'alert-circle': IconAlertCircle,
  'alert-circle-filled': IconAlertCircleFilled,
  help: IconHelpCircle,

  // reading / domain
  book: IconBook,
  'book-2': IconBook2,
  vocabulary: IconVocabulary,
  blockquote: IconBlockquote,
  barcode: IconBarcode,
  notebook: IconNotebook,
  'reading-log': IconNotebook,
  flame: IconFlame,
  'flame-filled': IconFlameFilled,
  shield: IconShield,
  'shield-check': IconShieldCheck,
  calendar: IconCalendar,
  'calendar-event': IconCalendarEvent,
  'calendar-stats': IconCalendarStats,
  clock: IconClock,
  timer: IconStopwatch,
  history: IconHistory,
  user: IconUser,
  'user-plus': IconUserPlus,
  'user-off': IconUserOff,
  users: IconUsers,
  flag: IconFlag,
  'flag-filled': IconFlagFilled,
  trophy: IconTrophy,
  award: IconAward,
  badge: IconBadge,
  medal: IconMedal,
  certificate: IconCertificate,
  gift: IconGift,
  ticket: IconTicket,
  qrcode: IconQrcode,
  puzzle: IconPuzzle,
  target: IconTarget,
  star: IconStar,
  'star-filled': IconStarFilled,
  rating: IconStar,
  bolt: IconBolt,
  heart: IconHeart,
  'heart-filled': IconHeartFilled,
  crown: IconCrown,
  rocket: IconRocket,
  leaf: IconLeaf,

  // actions
  settings: IconSettings,
  gear: IconSettings,
  pencil: IconPencil,
  edit: IconPencil,
  writing: IconWriting,
  copy: IconCopy,
  duplicate: IconCopy,
  trash: IconTrash,
  archive: IconArchive,
  link: IconLink,
  unlink: IconUnlink,
  'plug-connected': IconPlugConnected,
  eye: IconEye,
  'eye-off': IconEyeOff,
  search: IconSearch,
  filter: IconFilter,
  download: IconDownload,
  printer: IconPrinter,
  upload: IconUpload,
  pin: IconPin,
  'pin-filled': IconPinFilled,
  signature: IconSignature,

  // content / objects
  sparkles: IconSparkles,
  bulb: IconBulb,
  speakerphone: IconSpeakerphone,
  megaphone: IconSpeakerphone,
  sun: IconSun,
  moon: IconMoon,
  smile: IconMoodSmile,
  lock: IconLock,
  message: IconMessageCircle,
  'message-circle': IconMessageCircle,
  'message-check': IconMessageCircleCheck,
  'message-x': IconMessageX,
  messages: IconMessages,
  'message-chatbot': IconMessageChatbot,
  microphone: IconMicrophone,
  volume: IconVolume,
  'volume-off': IconVolumeOff,
  'player-stop-filled': IconPlayerStopFilled,
  'play-filled': IconPlayerPlayFilled,
  'pause-filled': IconPlayerPauseFilled,
  'rewind-backward-15': IconRewindBackward15,
  'rewind-forward-15': IconRewindForward15,
  confetti: IconConfetti,
  apple: IconApple,
  send: IconSend,
  inbox: IconInbox,
  'file-text': IconFileText,
  'clipboard-check': IconClipboardCheck,
  'clipboard-list': IconClipboardList,
  list: IconList,
  'list-numbers': IconListNumbers,
  'align-left': IconAlignLeft,
  paragraph: IconAlignLeft,
  scribble: IconScribble,
  wave: IconWaveSine,
  quote: IconQuote,
  code: IconCode,
  photo: IconPhoto,
  'plug-off': IconPlugOff,
  palette: IconPalette,
  'zoom-in': IconZoomIn,
  'zoom-out': IconZoomOut,

  // layout / structure
  route: IconRoute,
  'dice-5': IconDice5,
  'layout-grid': IconLayoutGrid,
  'layout-dashboard': IconLayoutDashboard,
  layout: IconLayout,
  'layout-columns': IconLayoutColumns,
  'layout-bottombar': IconLayoutBottombar,
  layers: IconStack2,
  atom: IconAtom,
  forms: IconForms,
  browser: IconBrowser,

  // data / analytics
  'chart-bar': IconChartBar,
  'chart-column': IconChartColumn,
  'chart-line': IconChartLine,
  'trending-up': IconTrendingUp,
  'report-analytics': IconReportAnalytics,

  // places / sync
  school: IconSchool,
  building: IconBuilding,
  'building-community': IconBuildingCommunity,
  'arrows-exchange': IconArrowsExchange,
  'switch-horizontal': IconSwitchHorizontal,
  swap: IconSwitchHorizontal,
  refresh: IconRefresh,

  // safety / wellbeing / notifications
  bell: IconBell,
  'bell-ringing': IconBellRinging,
  mail: IconMail,
  email: IconMail,
  phone: IconPhone,
  'phone-call': IconPhoneCall,
  lifebuoy: IconLifebuoy,
  'mood-sad': IconMoodSad,
  'mood-cry': IconMoodCry,
  'mood-happy': IconMoodHappy,
  'mood-neutral': IconMoodNeutral,
  'heart-handshake': IconHeartHandshake,
  'shield-heart': IconShieldHeart,
  'shield-alert': IconShieldExclamation,
  'flag-off': IconFlagOff,
  snowflake: IconSnowflake,
  'rosette-discount-check': IconRosetteDiscountCheck,
  'external-link': IconExternalLink,
  maximize: IconMaximize,
  ban: IconBan,
  'verified-badge': IconRosetteDiscountCheckFilled,
  'circle-minus': IconCircleMinus,
  'user-up': IconUserUp,
  key: IconKey,
  hourglass: IconHourglass,
  id: IconId,
  minimize: IconMinimize,
  heartbeat: IconHeartbeat,
  'activity-pulse': IconActivityHeartbeat,
  'user-shield': IconUserShield,
  'message-report': IconMessageReport,
  'first-aid': IconFirstAidKit,
  'alert-hexagon': IconAlertHexagon,

  // book discovery
  headphones: IconHeadphones,
  'device-desktop': IconDeviceDesktop,
  'device-mobile': IconDeviceMobile,
  'device-tablet': IconDeviceTablet,
  movie: IconMovie,
  news: IconNews,
  bookmark: IconBookmark,
  'bookmark-filled': IconBookmarkFilled,
  compass: IconCompass,
  'thumb-up': IconThumbUp,
  'thumb-up-filled': IconThumbUpFilled,
  share: IconShare,
  checks: IconChecks,

  // pick your path (learning destinations)
  'ball-basketball': IconBallBasketball,
  tools: IconTools,
  paw: IconPaw,
  fish: IconFish,
  trees: IconTrees,
  'building-monument': IconBuildingMonument,
  'building-arch': IconBuildingArch,
  gauge: IconGauge,
  ruler: IconRuler,
  run: IconRun,
}

export const ICON_NAMES = Object.keys(REGISTRY)

export function Icon({ name, size = 18, stroke = 1.8, className, ...rest }) {
  const Glyph = REGISTRY[name]
  if (!Glyph) {
    if (import.meta.env.DEV) console.warn(`<Icon>: unknown name "${name}"`)
    return null
  }
  return (
    <Glyph
      size={size}
      stroke={stroke}
      className={className ? `bp-icon ${className}` : 'bp-icon'}
      {...rest}
    />
  )
}
